### ISSUE TITLE
Access to Kubernetes API

### ISSUE THREAD

**Issue by estahn** [Dynatrace/dynatrace-operator#102]
I tried to configure access to the Kubernetes API but the required certificates are not wired up:

```
dynakube-kubemon-0 dynatrace-operator 2021-03-26 00:05:40 UTC INFO [<mud10346>] [<com.compuware.apm.debug.apiconnector.kubernetes>, KubernetesFastCheck] Fast check failed for endpoint https://kubernetes.default.svc/api with SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target [Suppressing further identical messages for 1 hour]
```

**Comment by DTMad** [comment]
Hey @estahn 

Thanks for your feedback, we already know about that.
This is not possible as of now but we are working on a solution already.

Will let you know once we have it available.

**Comment by Marki4711** [comment]
Are there any updates on the issue? I got the error too.

**Comment by chrismuellner** [comment]
This is now supported with the release of v0.3.0
