### ISSUE TITLE
metadata.labels must be no more than 63 characters

### ISSUE THREAD

**Issue by hbuckle** [Dynatrace/dynatrace-operator#1082]
We are seeing the following error in our cluster logs

```
create Pod cbuk-core-staginggreen-preview-aks-uksouth-activegate-0 in StatefulSet cbuk-core-staginggreen-preview-aks-uksouth-activegate failed error: Pod "cbuk-core-staginggreen-preview-aks-uksouth-activegate-0" is invalid: metadata.labels: Invalid value: "cbuk-core-staginggreen-preview-aks-uksouth-activegate-6c698bf49d": must be no more than 63 characters
```

Do we need to ensure the Dynakube name field is not longer than a certain amount?

**Comment by chrismuellner** [comment]
Yes, Activegate and Oneagent pods are created by using the Dynakube name and appending `oneagent`/`activegate`, e.g. `<dynakube>-activegate-<pod>` or `<dynakube>-oneagent-<pod>`

**Comment by hbuckle** [comment]
So this was previously working but seems to have stopped earlier today - has the hash on the end of the label changed?

If the hash can change, then what is the maximum dynakube name length?

**Comment by chrismuellner** [comment]
What version of the Operator are you using?
Are you setting these labels yourself in the activegate section of the Dynakube?

This label is not set by the Operator when creating the Activegate and sincehis is a pod created by a statefulset, you should not even have a pod hash there.

**Comment by chrismuellner** [comment]
Shortening the name sounds like a good workaround, we'll try to make this more straight forward in the future.

**Comment by hbuckle** [comment]
If it is possible to just shorten the name of the StatefulSet internally that would be great, then we aren't limited by the Dynakube name

**Comment by chrismuellner** [comment]
Workaround exists by using a shorter Dynakube name.

We are talking internally how to make this more straight forward in the future.
