### ISSUE TITLE
Getting Failed to watch and failed to list *v1beta1.DynaKube error when upgrading version to v.0.8.0 

### ISSUE THREAD

**Issue by aleexx17** [Dynatrace/dynatrace-operator#1093]
Hello 

Since we're running a pretty old version of the dynatrace-operator (v.0.2.2), I've wanted to upgrade the version to v.0.8.0. 

With the new version the dynatrace-operator Pod often crashes. In the logs the following is shown: 

```Bash
W0825 11:34:38.671883       1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.23.1/tools/cache/reflector.go:167: failed to list *v1beta1.DynaKube: conversion webhook for dynatrace.com/v1alpha1, Kind=DynaKube failed: Post "https://dynatrace-webhook.dynatrace.svc:443/convert?timeout=30s": EOF
```
I've tried to resolve the problem by following the official troubleshooting guide, but it still doesn't work. 
(https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/troubleshoot-k8s-setup-config-and-monitoring-issues)

Thanks for any tips :) 

Alex

**Comment by luhi-DT** [comment]
HI, how did you upgrade to 0.8, on OLM there should not be an actual direct upgrade path from 0.2.2 to 0.8. Thanks!

**Comment by aleexx17** [comment]
Hi, so right now I've deployed the version 0.7.2 wich works like a dream without this weird error :) 
So for me this issue is resolved because I have now a newer version running. 
But thank you very much for your help!
