### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error when running on ARM

### ISSUE THREAD

**Issue by rscottwatson** [Dynatrace/dynatrace-operator#1117]
Using the latest version of the Operator doesn't work on ARM nodes. v.0.8.2

We have both AMD and ARM nodes and the ARM node fails with the above error.

I have tried to update the env var for the ONEAGENT POD using the following  https://www.dynatrace.com/support/help/shortlink/oneagent-docker#locate-your-oneagent-installer-url 

However, you are not allowed to change the environment variable so I was unable to supply the var ONEAGENT_INSTALLER_SCRIPT_URL for the single pod.

Does this mean we need 2 oneAgent sections in the Dynakube as shown in https://github.com/Dynatrace/dynatrace-operator/issues/454?

**Comment by 0sewa0** [comment]
The operator it self works on arm nodes, however there are a few limitations currently:
- In 0.8.2 (and earlier) the CSI driver may need extra tolerations to appear (example on GKE)
- The OS OneAgent and ActiveGate tenant registry do not support ARM
- Technology support for application monitoring OneAgents varies.

**Comment by project-administrator** [comment]
In that case, where should we get the OneAgent ARM images? It's failing to start.
