### ISSUE TITLE
Could we specify the PaaS OneAgent version in app-only without CSI driver?

### ISSUE THREAD

**Issue by KeaneYu** [Dynatrace/dynatrace-operator#1130]
Hi,
We are using application-only ingestion mode without CSI driver.
We want to use a specific PaaS OneAgent version insteand of the latest version. We tried specifying the version in dynakube.yaml, however, the "install-oneagent" init-container still using "latest" to download the latest version. Any idea?
![image](https://user-images.githubusercontent.com/14102746/188780873-fb76d36e-97f4-470f-9733-a26224da846a.png)

**Comment by luhi-DT** [comment]
Hi, unfortunatly this is currently onyl possible with the CSI Driver.

**Comment by KeaneYu** [comment]
Thank Lukas, please consider it as feature request.

**Comment by luhi-DT** [comment]
Hi, with 0.9 we have released a fix for the behaviour and your issue should be resolved. Thanks!
