### ISSUE TITLE
New versions of the chart not present on ArtifactHub

### ISSUE THREAD

**Issue by pierluigilenoci** [Dynatrace/dynatrace-operator#1146]
The latest version of the chart is [0.8.2](https://github.com/Dynatrace/dynatrace-operator/releases/tag/v0.8.2) but on [ArtifactHUB](https://artifacthub.io/packages/helm/dynatrace/dynatrace-operator) the chart is stuck at [0.7.2](https://artifacthub.io/packages/helm/dynatrace/dynatrace-operator).

**Comment by luhi-DT** [comment]
It was because the URL was still pointing to the old helm charts repo: Its now up to date: https://artifacthub.io/packages/helm/dynatrace/dynatrace-operator
