### ISSUE TITLE
The server could not find the requested resource

### ISSUE THREAD

**Issue by Govin87** [Dynatrace/dynatrace-operator#1160]
Hi, 
Please help, we are getting below error while installing dynatrace-webhook through below deployment yml on Azure AKS. Webhook pods are CrashLoopBackOff.
.
kubectl apply -f https://github.com/Dynatrace/dynatrace-operator/releases/latest/download/kubernetes.yaml

 kubectl logs  deployment.apps/dynatrace-webhook -n dynatrace
Found 2 pods, using pod/dynatrace-webhook-64f4944887-g42rr
{"level":"info","ts":"2022-09-16T07:19:23.212Z","logger":"dynatrace-operator-version","msg":"dynatrace-operator","version":"v0.7.3","gitCommit":"199c15ecadb72bcd5289b4eb541e8c644cb3bbe7","buildDate":"2022-09-08T08:52:39+00:00","goVersion":"go1.18.6","platform":"linux/amd64"}
I0916 07:19:24.263554       1 request.go:665] Waited for 1.004150871s due to client-side throttling, not priority and fairness, request: GET:https://10.41.80.1:443/apis/kibana.k8s.elastic.co/v1?timeout=32s
{"level":"info","ts":"2022-09-16T07:19:27.217Z","logger":"main.controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8383"}
{"level":"info","ts":"2022-09-16T07:19:27.217Z","logger":"main","msg":"SSL certificates configured","dir":"/tmp/k8s-webhook-server/serving-certs/","key":"tls.key","cert":"tls.crt"}
{"level":"info","ts":"2022-09-16T07:19:27.232Z","logger":"main.controller-runtime.webhook","msg":"Registering webhook","path":"/label-ns"}
{"error":"unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: an error on the server (\"Internal Server Error: \\\"/apis/external.metrics.k8s.io/v1beta1?timeout=32s\\\": the server could not find the requested resource\") has prevented the request from succeeding","level":"error","logger":"main","msg":"webhook-server setup failed","stacktrace":"github.com/go-logr/logr.Logger.Error
        /go/pkg/mod/github.com/go-logr/logr@v1.2.2/logr.go:270
main.exitOnError
        /app/src/cmd/operator/main.go:109
main.main
        /app/src/cmd/operator/main.go:82
runtime.main
        /usr/local/go/src/runtime/proc.go:250","ts":"2022-09-16T07:19:31.237Z"}

Thanks in advance

**Comment by chrismuellner** [comment]
metrics api has to be available on your cluster, see [official docs on troubleshooting](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/troubleshoot-k8s-setup-config-and-monitoring-issues#expand--unable-to-retrieve-the-complete-list-of-server-apis)

note: don't use `latest` tag, but either follow official documentation or check releases to find latest version that should be used (currently `v0.8.2`)!
