### ISSUE TITLE
Helm chart doesn't place CRDs in correct folder

### ISSUE THREAD

**Issue by tonedefdev** [Dynatrace/dynatrace-operator#1168]
In order to allow Helm to deploy CRDs they need to be in a specific folder called `crds` currently the CRDs are placed in a folder called `generated` so Helm will not deploy the CRDs. As a result brand new clusters using these Helm charts will likely fail until the required CRD has been manually applied. This can be easily fixed by placing this in the correct folder that Helm expects for CRDS.

Documentation: [Helm CRDs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you)

**Comment by chrismuellner** [comment]
Our CRD ends up in `templates/Common/crd` and can be installed when using the `installCRD` flag.

The `crds` folder used by Helm does not support upgrading the CRDs if it already exists on the Cluster.
