### ISSUE TITLE
Enhance troubleshoot documentation and functionality, dynakube name differs from OOTB installation in Dynatrace

### ISSUE THREAD

**Issue by sergiohinojosa** [Dynatrace/dynatrace-operator#1224]
Hi guys,

I find great that there is a troubleshoot command that can be executed but please enhance the documentation and the troubleshooting since it won't work with most of the Dynatrace OOTB installations without passing any arguments.

`kubectl exec deploy/dynatrace-operator -n dynatrace -- dynatrace-operator troubleshoot
`

When installing Dynatrace with the UI of Dynatrace, is required to set a name. The name will be the name of the Dynakube object. Rarely a customer will name the installation of a cluster "dynakube". When the troubleshoot command is executed it searchs by default in the `namespace=dynatrace` and `dynakube=dynakube`
```
kubectl exec deploy/dynatrace-operator -n dynatrace -- dynatrace-operator troubleshoot
{"level":"info","ts":"2022-10-07T15:10:50.879Z","logger":"dynatrace-operator-version","msg":"dynatrace-operator","version":"v0.9.0","gitCommit":"99a1efbe21f7bf566be7412fe20d61a489d6333c","buildDate":"2022-09-28T13:57:47+00:00","goVersion":"go1.19.1","platform":"linux/amd64"}
[namespace ] 	--- checking if namespace 'dynatrace' exists ...
[namespace ] 	 √  using namespace 'dynatrace'
[dynakube  ] 	--- checking if 'dynatrace:dynakube' Dynakube is configured correctly
[dynakube  ] 	    CRD for Dynakube exists
[dynakube  ] 	 ×  selected 'dynatrace:dynakube' Dynakube does not exist {"error": dynakubes.dynatrace.com "dynakube" not found}
[dynakube  ] 	 ×  'dynatrace:dynakube' Dynakube isn't valid

```
there is a dynakube object called traeffik, so when doing

`kubectl exec deploy/dynatrace-operator -n dynatrace -- dynatrace-operator troubleshoot --namespace=dynatrace --dynakube=traeffik`

it works.

make it so that the dynakubes are search from the namespace of the pod and then the found dynakube is analysed. The namespace is also default "dynatrace". In corporate installations this won't be the case. Now, if you improve it  by getting the namespace from the ENV variable of the Operator container then it will always work. 

`kubectl get dynakubes.dynatrace.com -n dynatrace
`

In the meantime update the documentation with the two flags that can be passed in the command. I had to take a look at the code see how to make it work. 

Later please improve the functionality by removing/enhancing the namespace and taking it from the container environment variable so it does the analysis on the dynakube from that same namespace.

Thanks
Sergio

**Comment by chrismuellner** [comment]
Starting with v0.10.0 all Dynakubes in the Operator namespace or provided namespace will be analyzed, if no `--dynakube` parameter is given. Dynakubes in other namespace are not reconciled by the Operator.
When no `--namespace` parameter is provided, the default namespace has always been the same as the Operator pod is running in.

If you need more information about the troubleshoot command check out our [official documentation].(https://www.dynatrace.com/support/help/shortlink/kubernetes-troubleshoot#troubleshoot)
