### ISSUE TITLE
Set ActiveGate version

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/dynatrace-operator#1234]
In the Custom Resource, currently only the OneAgent has the options to disable automatic update and set a specific version.

Is there a plan to allow this for the Active Gates aswell?

**Comment by luhi-DT** [comment]
Hi, that is already possible by setting the image of the activeGate to a custom one. This can also be done by setting it to a fixed version from the Dynatrace Cluster. You can set it in the customResource like that ` image: <your_environment_domain_name>/linux/activegate:<activegate_version>`  

More information here: https://www.dynatrace.com/support/help/shortlink/air-gapped-kubernetes#immu-3

**Comment by pahofmann** [comment]
Ah right, the image is versioned corresponding to the AG version I actually already used that..:man_facepalming: 
Thanks!
