### ISSUE TITLE
Custom OneAgent Image not working

### ISSUE THREAD

**Issue by schlapzz** [Dynatrace/dynatrace-operator#1239]
I tried to deploy Dynatrace in an OpenShift Cluster. Because we can only pull Images from our internal Registry, I set the `.spec.cloudNativeFullStack.image` to point to our internal registry. But unfortunately the Operator refuse to pull this image.

If I run the troubleshoot command on the Operator, I got following error:
 `invalid image - registry not fount (myregistry.foo.bar/docker-io/dynatrace/oneagent:1.68.1000)`

According to this piece of code, the Operator checks if the  image path contains the string `linux`
https://github.com/Dynatrace/dynatrace-operator/blob/master/src/cmd/troubleshoot/image_pullable.go#L266-L271

Is this intentional?

**Comment by luhi-DT** [comment]
Hi, the troubleshoot script has a known problem there, but thanks for pointing out. However the initial error that the image is not pullable does not stand in correlation with that. Do you have oneagent pods, which are getting `ImagePullBackoff` or what problem are you facing?

**Comment by schlapzz** [comment]
No, you are totally right. The issue doesn't affect the oneAgent pods/containers. The init  container for the pods is pulling the image without any errors. So as you said, the error occures only in the troubleshoot script.

**Comment by luhi-DT** [comment]
Thanks for you confirmation, will close that issue as we already have an internal issue created for this. Thanks!
