### ISSUE TITLE
hostMonitoring is consuming too much licenses

### ISSUE THREAD

**Issue by olljanat** [Dynatrace/dynatrace-operator#1289]
It looks to be that `hostMonitoring` mode does not currently include `--set-infra-only=true` flag for pods so they consume licenses same way as full stack when only infra mode licenses should be used:
https://www.dynatrace.com/support/help/monitoring-consumption/application-and-infrastructure-monitoring

Parameters on pod deployed by this controller:
![image](https://user-images.githubusercontent.com/6213926/199426605-e3ad436c-452f-48fe-a223-1793096b2975.png)

same node in Dynatrace:
![image](https://user-images.githubusercontent.com/6213926/199426899-de9271e6-bd37-4791-85ae-28c4d4455036.png)

**Comment by luhi-DT** [comment]
Hi, please reach out to the Dynatrace Support regarding your issue: https://support.dynatrace.com/ Thanks!

**Comment by olljanat** [comment]
@luhi-DT Why? It is clearly operator which sets those parameters:
https://github.com/Dynatrace/dynatrace-operator/blob/225c6a61ff727a9712b15b203953e71e89b3c0bb/src/controllers/dynakube/oneagent/daemonset/arguments.go#L58
https://github.com/Dynatrace/dynatrace-operator/blob/225c6a61ff727a9712b15b203953e71e89b3c0bb/src/controllers/dynakube/oneagent/daemonset/daemonset.go#L39

so why `--set-infra-only` would be anyway different?
