### ISSUE TITLE
Option to override the automatic host-id generation on K8s Nodes

### ISSUE THREAD

**Issue by reinhard-brandstaedter** [Dynatrace/dynatrace-operator#1324]
Hello,

Is there an option to override the host-id generation for the oneagent rolled out via the operator to k8s nodes?
I'm working with a dynamically sized K8s Cluster on GCP with preemptible nodes that can die at any time.
In Dynatrace this results in a VERY long host list over time as nodes come and go. For every Node a new host in created.

Now Dynatrace has this [host-id option](https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-oneagent/oneagent-configuration-via-command-line-interface#host-id) for some time already and I think it would make sense to leverage this to consolidate nodes into the same entities based on IP address for example.

E.g.:
all the hosts with the same name (host naming rule ending in the last octet of the IP address) would truly become one host entity instead of multiple. And I'd not get thousands of (inactive) host entities over time but only the size of my hosts IP pool)

<img width="903" alt="image" src="https://user-images.githubusercontent.com/10830223/202167417-08f02484-be7c-4cd4-9a86-0f363c00f8d9.png">

kR

**Comment by luhi-DT** [comment]
Hi, that is currently not possible. 

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!

**Comment by reinhard-brandstaedter** [comment]
> that is currently not possible.
Hence the feature request :-)

But this is rather inconsistent. Some feature requests are handled here, some are handled (or mostly forgotten and never followed up with) on the community.
The "official" OSS project page of the operator has been moved here, but discussed it should be on the community. That is tedious....
[But I created an RFE there](https://community.dynatrace.com/t5/Dynatrace-product-ideas/Option-to-override-the-automatic-host-id-generation-on-K8s-Nodes/idi-p/199105)

**Comment by pahofmann** [comment]
It hosuld work via OneAgent arugument _--set-host-id-source_, it's not listed under the [limitations ](https://www.dynatrace.com/support/help/shortlink/oneagent-docker#limitations). 

 @luhi-DT is there any reason why this argument shouldn't work?
