### ISSUE TITLE
Dynatrace-Operator installation in Kubernetes 

### ISSUE THREAD

**Issue by renjithtc** [Dynatrace/dynatrace-operator#1355]
We are installing the Dynatrace operator (Dynatrace Operator v0.9.1) for Production setup for K8S monitoring.
We observed that there are changes in the installation procedure of the newer version of Dynatrace Operator v0.9.1.

We are trying to do a Helm installation and when we run the deployment after making required changes to the values file… We see only operator, webhook and csi components deployed. But, missing active gate and oneagent. The helm doesn't contain the deployment file for these two components. Can you please suggest how to deploy active gate and one agent.

Regards,
Renjith

**Comment by luhi-DT** [comment]
Hi,
please read the instructions in our official docu here: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm

It mentions every step needed to deploy the latest version.
Thanks

**Comment by renjithtc** [comment]
Hello Luhi, 

We followed that document, but it does not deploy ActiveGate and Oneagent.

**Comment by luhi-DT** [comment]
Hi,
Then this is a support request.
Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
