### ISSUE TITLE
Minor copy-paste error in all the samples.

### ISSUE THREAD

**Issue by Jaykul** [Dynatrace/dynatrace-operator#1372]
You're saying `set ``YOUR_ENVIRONMENT_ID` but then in the actual config, it's "ENVIRONMENTID" like:

```
  # For SaaS, set `YOUR_ENVIRONMENT_ID` to your environment ID.
  # For Managed, change the apiUrl address.
  # For instructions on how to determine the environment ID and how to configure the apiUrl address, see https://www.dynatrace.com/support/help/reference/dynatrace-concepts/environment-id/.
  apiUrl: https://ENVIRONMENTID.live.dynatrace.com/api
```
E.g. https://github.com/Dynatrace/dynatrace-operator/blob/2b9a13edd8c21d2652f1e0db431c34242ad2c584/assets/samples/classicFullStack.yaml#LL7-L11C55

**Comment by gkrenn** [comment]
This inconsistency should indeed be removed, thanks!
