### ISSUE TITLE
Should installCRD default to TRUE for helm chart?

### ISSUE THREAD

**Issue by Jaykul** [Dynatrace/dynatrace-operator#1373]
Yesterday I did my first deployment of this to a cluster, and I can't understand why you've got installCRD set to false by default. 

The CRD **must** be installed, or the Helm chart will fail.  **Why would I want to** manually install the CRD before the Helm chart? Is this a hang-over from Helm 2?

![image](https://user-images.githubusercontent.com/192942/204844100-2b3c563d-a040-403d-9f1f-052988458e1d.png)

**Comment by gkrenn** [comment]
If you enable `installCRD` the CRD is managed by helm, which has the implication that as soon as you uninstall with helm, DynaKube objects will be deleted too. - Per default, it is not our intention to delete configuration, which your DynaKubes are. Therefore you have to install the CRD before the actual helm chart.

Nevertheless you have the possibility to change this by using `installCRD=true`. 

For reference see [cert-manager](https://cert-manager.io/docs/installation/helm/#3-install-customresourcedefinitions), that took the same approach.
