### ISSUE TITLE
Dynakube to have ability to set no_proxy

### ISSUE THREAD

**Issue by luigiaparicio** [Dynatrace/dynatrace-operator#1428]
**Is your feature request related to a problem? Please describe.**
Dynakube has the ability to set proxy setting but not no_proxy

**Describe the solution you'd like**
I would like to specify the no_proxy settings inside Dynakube CR

**Describe alternatives you've considered**
Setup no_proxy setting inside Dynakube spec.proxy

**Additional context**
In my environment I need to setup Internet Proxy to access Dynatrace SaaS

**Comment by luhi-DT** [comment]
Hi, the NO_Proxy support is already on the roadmap, therefor i will close this ticket to avoid duplications.

Thanks for reaching out!
Lukas
