### ISSUE TITLE
synthetic active gateway 

### ISSUE THREAD

**Issue by Alansyf** [Dynatrace/dynatrace-operator#1435]
**Is your feature request related to a problem? Please describe.**
I have tried to use the lates release v0.10.1, just wanna get feature `capability=synthetic` but still getting: 

```
Error from server (
1 error(s) found in the Dynakube
 1. The DynaKube's specification tries to use an invalid capability in ActiveGate section, invalid capability=synthetic.
Make sure you correctly specify the ActiveGate capabilities in your custom resource.
...
...
```

This seems to me this feature already merged into master branch through [PR](https://github.com/Dynatrace/dynatrace-operator/pull/1357/files#diff-0cb9f15ed8153b5ea4ef3cff8a8ca2b582052a36e94774593add973e7c44fa62) but not in [release v0.10.1 ](https://github.com/Dynatrace/dynatrace-operator/blob/v0.10.1/src/api/v1beta1/activegate_types.go) ?

When can we expect this be released? To make private synthetic active gateway in k8s flavor is very important for us.

**Comment by chrismuellner** [comment]
Support for the Synthetic capability in the Activegate will be part of a future feature-release of the Dynatrace Operator. We don't release additional features as part of a bugfix release.
