### ISSUE TITLE
Expired certificate in dynatrace-webhook-certs secret on OpenShift

### ISSUE THREAD

**Issue by skrystos** [Dynatrace/dynatrace-operator#1442]
**Describe the bug**
Customer had instrumented environment with operator in version 0.6. He upgraded to version 10 because they had issues with working of environment after restart. The see error: 

<img width="591" alt="image" src="https://user-images.githubusercontent.com/116382985/210557075-dd1099aa-7d8a-4580-84b1-1a4a66dccb7e.png">

After some digging it turnes out that certificate for domain dynatrace-webhook.dynatrace.svc in secret dynatrace-webhook-certs is expired and reinstallation does not recreate this secret. 

**To Reproduce**

We don't have such issues on different envrionments so we don't know how to reproduce it. Customer is using dynakube.yaml like this:

apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: mtauron
  namespace: dynatrace
  labels:
    app.kubernetes.io/instance: <label_name>
spec:
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
  apiUrl: >-
    <apiurl>
  namespaceSelector:
    matchLabels:
      dynatrace: monitoring
  oneAgent:
    applicationMonitoring:
      useCSIDriver: false
  skipCertCheck: true
  tokens: <tokenname>

We need steps to recreate this secret, or force to use different domain name for which secret is present. Customer tried delete all secrets and start from 0 but didn't help. 

**Expected behavior**
Bring back monitoring

**Comment by chrismuellner** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
