### ISSUE TITLE
pull secret is missing: secrets "XXX-pull-secret" not found

### ISSUE THREAD

**Issue by melcsanad** [Dynatrace/dynatrace-operator#1481]
**Describe the bug**
We have succescfuly installed the Dynatrace Operator to Openshift (version: 4) test environment.
But Prod install fails with following error:
dynatrace:XXXX-pull-secret' pull secret is missing: secrets "XXXX-pull-secret" not found

**To Reproduce**
Run the following command:
oc adm new-project --node-selector="" dynatrace
oc apply -f https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.10.0/openshift.yaml
oc -n dynatrace wait pod --for=condition=ready --selector=app.kubernetes.io/name=dynatrace-operator,app.kubernetes.io/component=webhook --timeout=300s
oc apply -f dynakube.yaml

dynakube.yaml was generated by Dynatrace Managed Environemnt (version: 1.256.125)
apiVersion:` v1
data:
  apiToken: ZHQw...jJE

kind: Secret
metadata:
  name: xxxx-prod
  namespace: dynatrace
type: Opaque

apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: smart-prod
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
spec:
  apiUrl: https://dynar.service.org/e/9...e/api

**Expected behavior**
Operator Activegate starts up and connects to Dynatrace

**Screenshots**
0116 20:11:57.582976      16 request.go:682] Waited for 1.041367766s due to client-side throttling, not priority and fairness, request: GET:[https://10.95.0.1:443/apis/security.internal.openshift.io/v1?timeout=32s](https://x.x.x.x/apis/security.internal.openshift.io/v1?timeout=32s)
[namespace ]    --- checking if namespace 'dynatrace' exists ...
[namespace ]     ✓  using namespace 'dynatrace'
[crd       ]    --- checking if CRD for Dynakube exists ...
[crd       ]     ✓  CRD for Dynakube exists
[          ]    no Dynakube specified - checking all Dynakubes in namespace 'dynatrace'
[          ]    xxxx-prod
[dynakube  ]     |--- checking if 'dynatrace:xxxx-prod' Dynakube is configured correctly
[dynakube  ]     |    using 'dynatrace:xxxx-prod' Dynakube
[dynakube  ]     |    checking if api url is valid
[dynakube  ]     |    api url is valid
[dynakube  ]     |    'dynatrace:xxxx-prod' secret exists
[dynakube  ]     |    secret token 'apiToken' exists
[dynakube  ]     | X  'dynatrace:xxxx-prod-pull-secret' pull secret is missing: secrets "xxxx-prod-pull-secret" not found
[dynakube  ]     | ⚠  Skipped 'pullSecretHasRequiredTokens' check because prerequisites aren't met: [pullSecretExists]
[dynakube  ]     | X  'dynatrace:xxxx-prod' Dynakube isn't valid. Target namespace and dynakube can be changed by providing '--namespace <namespace>' or '--dynakube <dynakube>' parameters.: 'dynatrace:xxxx-prod-pull-secret' pull secret is missing: secrets "xxxx-prod-pull-secret" not found
[dynakube  ]     | ⚠  Skipped 'DynatraceClusterConnection' check because prerequisites aren't met: [dynakube]
[dynakube  ]     | ⚠  Skipped 'imagePullable' check because prerequisites aren't met: [dynakube]
[dynakube  ]     | ⚠  Skipped 'proxySettings' check because prerequisites aren't met: [dynakube]

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
