### ISSUE TITLE
CRD file for v0.10.2 contains bad Caracters "{{"

### ISSUE THREAD

**Issue by ddiawara** [Dynatrace/dynatrace-operator#1541]
**Describe the bug**
https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.10.2/dynatrace-operator-crd.yaml

```
 kaf dynatrace-operator-crd-v0.10.2.yaml -n dynatrace
error: error parsing dynatrace-operator-crd-v0.10.2.yaml: json: offset 2: invalid character '{' looking for beginning of object key string
```

![image](https://user-images.githubusercontent.com/62718811/218252935-e1aaf8f0-fd9c-404d-97fd-3dc67c278c9c.png)

**Comment by luhi-DT** [comment]
Hi @ddiawara, 
thanks for pointing out, we have fixed the manifests attached to our 0.10.2 release and already fixed the automated mechanism, that attaches those manifest for future releases.

Thanks a lot again,
Lukas
