### ISSUE TITLE
Support custom `repository` and tag `keys` in helm chart

### ISSUE THREAD

**Issue by xoanmi** [Dynatrace/dynatrace-operator#1561]
**Is your feature request related to a problem? Please describe.**
We would like to support and independent `repository` and `tag` keys in contrast to the currently supported `image` key

**Describe the solution you'd like**
The helm chart supports defining the `registry` and `tag` keys. If the `tag` key is not provided.Chart.AppVersion is used as a default.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by luhi-DT** [comment]
will close this issue as we have taken the discussion internally. Update on that topic, this feature will be part of the operator, but in a different way. More will follow soon.
