### ISSUE TITLE
Vulnerabilities in dynatrace-operator:v0.2.1

### ISSUE THREAD

**Issue by benj5656** [Dynatrace/dynatrace-operator#158]
Our security scan has detected some HIGH vulnerabilities which have been fixed in later versions of source packages.

Can these be fixed?
![image](https://user-images.githubusercontent.com/70276217/120817694-d6164400-c549-11eb-83eb-0346172d79a5.png)

**Comment by DTMad** [comment]
Hey @benj5656,
we will fix this with the next release.
Will inform you once the new release is available.

**Comment by DTMad** [comment]
Release got published some time ago:
https://github.com/Dynatrace/dynatrace-operator/releases/tag/v0.2.2
