### ISSUE TITLE
Helm Chart - image registry pull secret creation

### ISSUE THREAD

**Issue by AlexandreODelisle** [Dynatrace/dynatrace-operator#1633]
**Is your feature request related to a problem? Please describe.**

Currently the Helm Chart only permits to define the registry credentials outside of the dynatrace-operator chart. It does bring issue when trying to use the chart via a GitOps process where an application is bundle together.. 

We would need to define the registry credential prior to the dynatrace-operator helm chart deployment, which is odd. 

**Describe the solution you'd like**
The solution would consisce of a template of kind `Secret` with type  `kubernetes.io/dockerconfigjson` and a helper ( `.tpl` ) 

**Describe alternatives you've considered**
Currently, I need to apply the secret manifest prior to deploying the helm chart, and on the GitOps side I need to define multiple application only to handle a basic secret. 

I am willing to make the PR. 

Thanks,

**Comment by chrismuellner** [comment]
Thanks for the request, but we do not think this secret should be deployed as part of the helm chart.

You can set a custom image pull secret that exists by providing the `customPullSecret` value there, but creation of this custom pull secret is on your end and separate from the installation of the Dynatrace Operator. By allowing you to create the secret yourself you have the option to use any of the existing, secure ways of creating the secret the GitOps way!
