### ISSUE TITLE
hostMonitoring and csiDriver samples

### ISSUE THREAD

**Issue by Dynatrace-Jeroen-Hautekeete** [Dynatrace/dynatrace-operator#1676]
Hi - according to Dynatrace documentation, hostMonitoring also supports the use of csiDriver.
https://www.dynatrace.com/support/help/shortlink/dto-deploy-options-k8s#storage

Can the default value be added to the samples as an indication that this possibility exists ?

And as for the remark about oneagent versions on that page : when mutliple dynakubes are deployed, which 'version' will take precedence, or can the csiDriver support multiple versions for multiple dynakubes at once ? (e.g. mix of production/acceptance workloads reporting to separate monitoring environments ?)

**Comment by chrismuellner** [comment]
CSI driver is used by default for `hostMonitoring` and is already documented in the table you linked.

For additional help please reach out to [Dynatrace ONE support](https://support.dynatrace.com/).

Thanks!
