### ISSUE TITLE
apiextensions.k8s.io/v1beta1/CustomResourceDefinition is deprecated

### ISSUE THREAD

**Issue by anthu** [Dynatrace/dynatrace-operator#174]
Installing the Operator on newer Kubernetes environments is printing following warning:

```
 12:09:43.375044 207360 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
 12:09:43.428453 207360 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/dynakubes.dynatrace.com created
```

This issue is to track the migration of the apiVersion from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`

Reference: 
https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/

**Comment by DTMad** [comment]
Hey @anthu,
we are already working on a proper solution for this problem.
Will be handled in one of the upcoming PRs and fixed in the next release.
