### ISSUE TITLE
Disable automatic connection info pull from remote - How to?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [Dynatrace/dynatrace-operator#1758]
**Is your feature request related to a problem? Please describe.**
Hello team, I'm trying to find out how to disable the automatic connection info setup ( introduced by https://github.com/Dynatrace/dynatrace-operator/pull/1614 + https://github.com/Dynatrace/dynatrace-operator/pull/1691 ) which is currently setting the `DT_SERVER` environment variable on the activegate pod.

We are currently using this env var to point it to a custom AG on Dynatrace that we are allowed to reach through our infrastructure. The operator although is trying to use some internal names of Dynatrace AG that are not reachable from where the K8s cluster is deployed ( they live into two different network zones and there's a firewall that allows communication between them ). 

**Describe the solution you'd like**
I would appreciate if it is possible to disable this automatic detection and injection of these variables somehow. If already possible, then some documentation is missing. I did try to check your Go source code, as well as this repo for documentation going through the changelogs, and finally the Dynatrace official support documentations, but unfortunately I could find nothing about this feature. 

**Describe alternatives you've considered**
Another possible way would be to override which information is obtained by the operator on Dynatrace itself on the UI, but I wasn't able to find this part too. Feels like missing implementation, even though it would be harder then just a flag.

**Additional context**
N/A - but feel free to reach out to me if any question arises or something is not clear.

Thank you in advance and BR,
Julian

**Comment by luhi-DT** [comment]
Hi, thanks for reaching out :) 

We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!

**Comment by julianxhokaxhiu** [comment]
Hello @luhi-DT thanks for the reply. But is ONE Support also responsible for the operator code changes in case, if any?

**Comment by luhi-DT** [comment]
It will land on our desk eventually, but to me this looks like a strange setup, if you restrict your activeGate to specify only certain possible connection endpoints, but our support will help you with that :)

**Comment by julianxhokaxhiu** [comment]
Thank you, will approach them then. I have already another call planned still for some operator issues so I'll raise this up there. Cheers!
