### ISSUE TITLE
Feature "oneagent-initial-connect-retry-ms" doesn't work when injecting via dynakube to app deployments.

### ISSUE THREAD

**Issue by rocketsience21** [Dynatrace/dynatrace-operator#1819]
**Describe the bug**
I have configured a deployment of application that is behind istio-proxy in kubernetes cluster.  The proxy and application starting with difference in time above 6-7 second and dynatrace-operator that is injected to application container trying to connect to dynatrace servers to fetch some configuration(if i'm understand correctly logic of operator). As istio-proxy not ready when the dynatrace-operator making a call, operator failing to connect to server and throw DNS error:
 "2023-05-30 10:45:15.510 UTC [00000007] warning [native] Unable to do initial setup because no server is reachable. Last error: DNS resolution failed"
**and**
"2023-05-30 10:45:17.406 UTC [00000008] warning [native] Exception sending async messages: Not sent because last heartbeat failed."

When I'm configuring my application to "#hold_until_proxy_starts: true" everything fine wit dynatrace-operator, no DNS errors. However I can't wait for the proxy starts because of any issues with proxy happens application can wait endless. So I decided to enable the feature "oneagent-initial-connect-retry-ms" for dynatrace-operator, tried different delay-time from 6000 to 60000 ms but it doesn't help, injection of dynakube config is successful, dynatrace-operator in application container starting but connect retry for operator doesn't work. However when I'm adding manually parameter DT_INITIAL_CONNECT_RETRY_MS in deployment manifest of application, before redeployment,  with delay that allow proxy to be fully started, dynatrace-operator then works correctly no DNS errors. Version of dynatrace-operator is 0.11.2.
When I'm doing an injection via dynakube I can't find parameter DT_INITIAL_CONNECT_RETRY_MS in application container

**To Reproduce**
-Deploy dynakube config to k8s cluster(CRDs)
-Redeploy or deploy new application
-Check that injection was successful
-Check logs of dynatrace-operator

**Expected behavior**
Dynatrace-operator should do connection retries after some delay not immediately when container with application is started.

**Screenshots**
On the second screenshot you can see enabled DT_INITIAL_CONNECT_RETRY_MS manually in deployment manifest with operator versin v0.9.1. I have updated the operator to v0.11.2
![Screenshot_20230530_142357](https://github.com/Dynatrace/dynatrace-operator/assets/135016802/68479449-57e5-4f53-989d-e31411107b3a)
![Screenshot_20230530_143818](https://github.com/Dynatrace/dynatrace-operator/assets/135016802/7b92847a-f4cb-448f-a717-49fba51f0309)
![Screenshot_20230530_144929](https://github.com/Dynatrace/dynatrace-operator/assets/135016802/2ca10879-ca90-49f4-8cc4-94bfa0e091a4)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

 - Version 113.0.5672.126

**Additional context**

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
