### ISSUE TITLE
Adding podAnnotations

### ISSUE THREAD

**Issue by maciej-wilczynski** [Dynatrace/dynatrace-operator#182]
Hello, i would like to attach IAM role using kube2iam so it would be nice to have ability to append some annotations into Active Gate stateful set.

**Comment by baichinger** [comment]
Hi! Should those annotations be on the STS or rather be on Pods?

1. Would a set of global annotations applied to all workloads (and therefore Pods) created fulfill your needs?
2. Is OPA Gatekeeper or Kyverno an option for doing the mutation?

**Comment by maciej-wilczynski** [comment]
Hi, thank for your response. I meant the Pod. Currently i'm using [kube2iam](https://github.com/jtblin/kube2iam), which watch on pod annotation to attach IAM role, also I considered [IRSA](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/) (that watch ServiceAccount annotation) as i'm using EKS. I have to check Gatekeeper or Kyverno if any of them fit my cluster

**Comment by maciej-wilczynski** [comment]
@baichinger kyverno works perfectly here, but it has small conflict with argo-cd, already fixed https://github.com/argoproj/argo-cd/pull/6109 and will be solved in 2.1 version. thanks
