### ISSUE TITLE
Enable "automatic-kubernetes-api-monitoring" in the sample dynakube.yaml file

### ISSUE THREAD

**Issue by pureBella** [Dynatrace/dynatrace-operator#1857]
**Is your feature request related to a problem? Please describe.**
I am confused. After I have I successfully deployed the Dynatrace Operator with classicFullStack and cloudNativeFullStack injection using the sample dynakube.yaml via links below, all pods are up and running in namespace `dynatrace`, but the k8s cluster does not show up in Dynatrace UI below Infrastructure-> Kubernetes. It takes time to search for solution in the documentation, and I need to add additional annotation into the dynakube.yaml file. 
I found by default the "kubernetes-monitoring" capabilities has already enabled in the sample file, it is better to also add the annotations in the sample. I also found the classicFullStack dynakube.yaml file downloaded from the Dynatrace UI (by clicking button "Connect automatically via Dynatrace Operator ") have the annotation.
https://github.com/Dynatrace/dynatrace-operator/blob/main/assets/samples/classicFullStack.yaml
https://github.com/Dynatrace/dynatrace-operator/blob/main/assets/samples/cloudNativeFullStack.yaml
https://www.dynatrace.com/support/help/shortlink/deploy-ag-dynatrace-op#connect-your-clusters-and-enable-monitoring

**Describe the solution you'd like**
Add the configuration as below (can be commented out, but let users enable easily instead of searching and browsing lots of documentation pages) into these sample dynakube.yaml files. 

**Describe alternatives you've considered**
The settings can be commented out or leave enabled there. 
Because by default, users will need to check the Dynatrace UI to see the status of the Kubernetes cluster.

**Additional context**
<img width="1037" alt="image" src="https://github.com/Dynatrace/dynatrace-operator/assets/41782111/1cada595-16c3-4e28-9418-f93894c69453">
<img width="693" alt="image" src="https://github.com/Dynatrace/dynatrace-operator/assets/41782111/06561635-775a-4668-996f-c915cff8a435">

**Comment by wepudt** [comment]
Hi
thanks for your suggestion- makes sense- we will add it.
