### ISSUE TITLE
Activegate image not working on ARM64

### ISSUE THREAD

**Issue by alittlec** [Dynatrace/dynatrace-operator#186]
Hi,

When executing a 'standard' operator install (i.e. using install.sh) on an arm64 cluster,  I get a crashloopback off on the activegate pod, with this image

Image:          XXXXX.live.dynatrace.com/linux/activegate:latest

Is this image multi-arch, does it support ARM64?

**Comment by DTMad** [comment]
The AG image does not support ARM64.
The Operator and the OneAgent do.
