### ISSUE TITLE
Operator-managed ActiveGate private synthetics and AWS monitoring

### ISSUE THREAD

**Issue by agentreno** [Dynatrace/dynatrace-operator#1891]
**Is your feature request related to a problem? Please describe.**

It's related to getting features like private synthetics and AWS monitoring as part of the ActiveGate installed by the operator.

**Describe the solution you'd like**

I'd like to be able to use the operator exclusively for ActiveGate installation and updates while still benefiting from capabilities like private synthetics and AWS monitoring.

**Describe alternatives you've considered**

As per the documentation I considered running an EC2 instance for AWS monitoring [as per this guide](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-cloud-platforms/amazon-web-services/amazon-web-services-integrations/cloudwatch-metrics), and for private synthetics I considered running an ActiveGate deployment in an EKS cluster [as per this guide](https://www.dynatrace.com/support/help/platform-modules/digital-experience/synthetic-monitoring/private-synthetic-locations/containerized-locations). The former is highly undesirable for a variety of reasons, and the latter involves managing another activegate outside of the operator (also slightly undesirable).

**Additional context**

I saw [this page](https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-activegate/capabilities) which suggests a containerised activegate supports all of the features I want, but I realise that's not the same as operator support.

I also saw previous issues related to this:
https://github.com/Dynatrace/dynatrace-operator/issues/1435
https://github.com/Dynatrace/dynatrace-operator/issues/1083

I just wanted to clarify the current state of play here in case things have changed since those were posted. Thanks in advance.

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. 

Dynatrace reviews feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours. It might also be that there is some plans already or something is already worked on. e.g synthetic is already in preview mode

Therefore in order to have a shorter cycle I'd suggest doing above and reach out to our Product Team directly via the Community.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!

**Comment by agentreno** [comment]
@luhi-DT hello, it's more about the current level of support in the operator. Happy to take it to the Dynatrace community if it turns out this feature is currently missing, could you just confirm the currently capabilities of the operator on these two features?

**Comment by luhi-DT** [comment]
As said, synthetic is in preview mode our Product team is currently onboarding interested customers and through the Dynatrace Community you will reach them directly :)

**Comment by agentreno** [comment]
@luhi-DT you didn't address the question about AWS monitoring in the operator-managed activegates?

**Comment by luhi-DT** [comment]
The containerised ActiveGate, that is managed by the operator is of course capable of doing AWS Monitoring, but its no yet a capability that is supported with a direct configuration within the DynaKube (like routing or kubernetes-monitoring). So the short answer is no its not a supported feature currently within the operator, but the ActiveGate is capable of doing it. Therefor the community can give you more hints on timelines and such :)

**Comment by agentreno** [comment]
@luhi-DT thanks! appreciate it. I'll take it to the community.
