### ISSUE TITLE
README Support lifecycle link broken. 

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/dynatrace-operator#1904]
The Link in the main README.md under `Support lifecycle`  to the `Dynatrace support lifecycle for Kubernetes and Openshift` is broken and return a 404.   
It should probably direct to `https://www.dynatrace.com/support/help/shortlink/support-model-k8s-ocp`.

**Comment by luhi-DT** [comment]
Hi, thanks for pointing out, did not notice that the link changed - fixed and updated.

Have a great day!
