### ISSUE TITLE
Automatically connect the Kubernetes API to Dynatrace

### ISSUE THREAD

**Issue by fdebuire** [Dynatrace/dynatrace-operator#194]
It would help if the operator could automatically take care of this installation step: https://github.com/Dynatrace/dynatrace-operator#enable-kubernetes-api-monitoring.

The issue is that the connection needs to be reconfigured every time the endpoint of a Kubernetes cluster changes, which can happen when the cluster is recreated for any reasons.

What do you think? Is it something that could be the responsibility of the operator?

**Comment by DTMad** [comment]
Hey @fdebuire,

we are already working on a fix for this.
It won't be done automatically by the operator but rather by the ActiveGate itself if it detects to run within a container.
I can't give an exact estimate on when this will be released but please stay tuned ;)
