### ISSUE TITLE
Please enable single-namespace mode on the OLM subscription

### ISSUE THREAD

**Issue by Jaykul** [Dynatrace/dynatrace-operator#1941]
**Is your feature request related to a problem? Please describe.**

When we install an operator like Elastic, it supports all of the InstallModes and [namespace scoping options](https://olm.operatorframework.io/docs/advanced-tasks/operator-scoping-with-operatorgroups/).

Dynatrace only works in AllNamespaces.

This is a problem for several reasons:

1. Creating the dynakube multiple times does not actually work, so there's no point in having the operator watch multiple namespaces.
2. If the operator is watching all namespaces, then _anyone_ who can create resources in _any_ namespace can (try to) create the dynakube anywhere.
3. When I check for `kubectl get csv -A` the dynatrace-operator shows up once for every namespace, even though it's really only valid in ... whichever namespace I first deploy the dynakube resource definition.

**Describe the solution you'd like**

I believe that for anyone using classic Full Stack or cloud native full stack deployments, the operator should support the OwnNamespace (and SingleNamespace) InstallMode.

Personally, I want to install the operator in the "dynatrace" namespace and have it create the activeGates and oneAgent in that same namespace, but I can see an argument for having the operator in a separate namespace, even though that's not how any of your documentation would do it. 

**Describe alternatives you've considered**

If you support creating multiple dynakube resources with their own activeGates sending to different dynatrace subscriptions, then it makes sense to keep "AllNamespaces" and add "MultipleNamespaces" as well as the "OwnNamespace" and "SingleNamespace"

**Additional context**

If nothing else, just enable all the modes, and let us pick the one we want. That's how the Elastic ECK operator works ;-)

**Comment by luhi-DT** [comment]
Hi, thanks for reaching out. The input is valid and we would love to do that however if you read through the docs closely you will find a limitation for Operators and respectively their CSVs, which says that if they feature a conversion webhook they may only support AllNamespaces. That is the only reason why we have to choose AllNamespaces, as the Dynatrace Operator have a conversion webhook that converts DynaKube's from v1alpha1 to v1beta1. We already talked to RedHat about that, but currently it stands as it is and i can't give an outlook if or when this will change.

For reference: https://olm.operatorframework.io/docs/advanced-tasks/adding-admission-and-conversion-webhooks/#conversion-webhook-rules-requirements

Thanks!

**Comment by ocpvkb** [comment]
Hello @luhi-DT ,
Is there any news on this topic?
Unfortunately, I have to agree with the previous speaker and add the following point:

Through the InstallMode "AllNamespaces" via OLM, Openshift automatically creates RBAC elements for the Dynatrace CRD APIs and inherits them to existing roles. This means that every user can create Dynakube instances as a member of this role, for example.
-->
https://docs.openshift.com/container-platform/4.14/operators/understanding/olm/olm-understanding-operatorgroups.html#olm-operatorgroups-rbac_olm-understanding-operatorgroups

If a user has managed to create oneagents in their namespace using Dynakube CR, they have full access to the host file system of the cluster nodes: (take a closer look at the volumes, securityContext and hostNetwork spec....)

This situation represents a massive security problem. !

**Comment by luhi-DT** [comment]
Hi, this limitation has not changed on RedHat side -> There is always the option to not opt for the OLM installation but to go with manifest or helm approach instead.

BR
