### ISSUE TITLE
dynatrace webhook pod crashes due to failure of liveness and readiness probe

### ISSUE THREAD

**Issue by krimeshshah** [Dynatrace/dynatrace-operator#1944]
**Describe the bug**
I am trying to install dynatrace webhook with dynatrace operator helm chart - https://github.com/Dynatrace/dynatrace-operator/tree/main/config/helm/chart/default. After successful deployement of the chart, i can see that operator pod is running but dynatrace-webhook pod is not running and crashes after sometime due to failure of readiness and liveness probe. With below error 
```
Readiness probe failed: Get "http://100.96.0.54:10080/readyz": dial tcp 100.96.0.54:10080: connect: connection refused
  Warning  Unhealthy  96s (x3 over 116s)  kubelet      
      Liveness probe failed: Get "http://100.96.0.54:10080/livez": dial tcp 100.96.0.54:10080: connect: connection refused
```
From the error looks like , the port liveness and readiness probe that webhook is trying to run is not open or available. hence i tried to change to couple of ports as well. But still doesn work

**To Reproduce**
1. Go to 'https://github.com/Dynatrace/dynatrace-operator/tree/main/config/helm/chart/default"
2. Click on 'Deploy the helm chart"

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luhi-DT** [comment]
Hi, are you using the official instructions to install the helm chart? https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm#install-helm

It looks like you are using the helm chart from main, but with the operator v0.12.0 image, which is not supported at all.

**Comment by luhi-DT** [comment]
Seems like you have used the wrong helm chart. I will proceed to close this issue.

If you need more assistance, please reach out via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.
Thanks!

**Comment by krimeshshah** [comment]
Hi

No i am using the right helm chart from dynatrace which is mentioned in the document.

Sorry for the delay in reply,

Regards,
krimesh

**Comment by krimeshshah** [comment]
Is this is the chart from main  https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/set-up-k8s-monitoring-helm#install-helm which is mentioned in the official document?
