### ISSUE TITLE
Issue with injection on Istio sidecar

### ISSUE THREAD

**Issue by kalioz** [Dynatrace/dynatrace-operator#1956]
**Describe the bug**
The injection on an Istio sidecar (envoy proxy) that is configured to use an applicative firewall (via an envoyFilter, our usage is [here](https://docs.fastly.com/signalsciences/install-guides/kubernetes/kubernetes-istio/#adding-the-istio-envoyfilter-object-to-inject-the-required-envoy-config-into-the-istio-proxy)) makes the envoy proxy exit with a segmentation fault.

**This is new behaviour for us since thursday 12 July; we're using fixed versions**.
- the bug stops reproducing if we remove the EnvoyFilter (no firewall)
- the bug stops reproducing if we disable Dynatrace on the namespace (no tracing)

**To Reproduce**
1. Use Istio on your namespace
2. Install an envoyfilter targeting signalscience
3. Configure Dynatrace to target the namespace using applicationMonitoring
4. execute any http request to the pod passing by Istio (not reproduced with a direct port-forward)
5. See error

**Expected behavior**
The segmentation fault shouldn't happen.

**Screenshots**
<img width="840" alt="error_istio_dynatrace" src="https://github.com/Dynatrace/dynatrace-operator/assets/24780504/a3334772-34ce-4542-849d-71d63e8cd2b9">

**Additional context**

Istio: reproduced on v1.16.4, v1.16.5, v1.17.3
Dynatrace-operator: reproduced on v0.10.2, v0.12.0
Once again, this is a new behaviour - everything worked well with our configurations before we started to see errors last thursday. The errors only starting occuring when we created new pods.

We also saw there's an ongoing incident with .NET applications, with a supposed fix in the 1.269.166 version - even with this version (1.269.166.20230715-203547), we still have this issue today.
![image](https://github.com/Dynatrace/dynatrace-operator/assets/24780504/e0a6b8d2-78e4-4737-92ee-7f8cd5d1f0ed)

A fix (for us) would have been to be able to disable the injection on some sidecars (we never use dynatrace to check Istio), but as far as i can see in the code this is not an existing functionality (yet ?) cf https://github.com/Dynatrace/dynatrace-operator/blob/2328a307c407168f5b319c8bd278a92409bab305/src/webhook/mutation/pod_mutator/oneagent_mutation/containers.go#L50

**Comment by chrismuellner** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
