### ISSUE TITLE
Adding trusted Root CAs to activegate

### ISSUE THREAD

**Issue by dm185372** [Dynatrace/dynatrace-operator#201]
Hello, i am following your guide here to connect my Dynatrace SAAS platform to our eks cluster: https://github.com/Dynatrace/dynatrace-operator, however on the last step in the Dynatrace UI, i am getting "There was an error with the TLS handshake: The specified certificate is not trusted". I know under normal circumstances on an Activegate i can do this https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-activegate/configuration/configure-trusted-root-certificates-on-activegate/, but how can i mount a keystore to my activegate pod? There does not seem to be an option to add a volume to it in the cr.yaml.

**Comment by DTMad** [comment]
Hey @dm185372 
the containerized AG as of now is not able to take a custom certificate.
We already implemented this and it will be released with the next release of the operator.

Please stay tuned until then

**Comment by dm185372** [comment]
Thanks for the response @DTMad - do you guys have any ETA when the next release will be? I can work around it until then, i am just wondering.

**Comment by DTMad** [comment]
We try our best to make it until end of Q3

**Comment by DTMad** [comment]
This duplicates https://github.com/Dynatrace/dynatrace-operator/issues/102
Will be fixed with 0.3.0
