### ISSUE TITLE
How to find be notified on which dynakube params to migrate?

### ISSUE THREAD

**Issue by 163a** [Dynatrace/dynatrace-operator#2017]
I upgraded to latest 0.12.1 Operator from 0.12.0. I had some issues somewhere between 0.10.x and 0.11.0 upgrades with cr.yaml accepting my `image` / `version` references for OA and AG, so I commented those out and re-applied and been happy days since, so I haven't had to make any changes to cr.yaml for a few Operator releases.

I am suddenly getting an issue, since I noticed my host group setting in args didn't get applied recently. I'm trying to apply that now but my whole CR seems to get rejected.

I cannot see in the release notes if there's been a manifest update, but it does seem to be the case that I cannot apply my cr.yaml changes file due to these issues:
strict decoding error: unknown field "spec.oneAgent.classicFullStack.enabled", unknown field "spec.oneAgent.classicFullStack.resources"
From what I can tell, Operator used to not care if remove features were still there, such as:
`serviceAccountName`
`useUnprivilegedMode`
`useImmutableImage`
There is a note about change from image to `imageRef` and I can only infer that resources was re-factored to oneAgentResources from here: https://www.dynatrace.com/support/help/shortlink/dto-params-k8s#spec-oneagent-classicfullstack

I would consider it an essential to have a migration note on this somewhere in the documentation (please point it out if I missed it!!) There are something like 5 configs deprecated/removed! A major update required to my CR! I would've last applied the CR around version 0.9.x or 0.10.x, so it's _not that old._

I would consider it a nice to have the configuration webhook auto-convert old config and handle the upgrade to new manifest version and/or log an output that these options are deprecated.

What is the current manifest version I need to set?

**Comment by luhi-DT** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
