### ISSUE TITLE
[operator v0.12.1, classicFullStack] OneAgent pods deployed on EKS/Bottlerocket AMI not running

### ISSUE THREAD

**Issue by ltomasik** [Dynatrace/dynatrace-operator#2047]
Hello team,
we tried to deploy Dynatrace operator v0.12.1 on AWS EKS 1.26.7 with classicFulStack configuration. Our worker nodes are running on Bottlerocket AMI and OneAgents having problem to start with following error. I found old issue [#376 ](https://github.com/Dynatrace/dynatrace-operator/issues/376) from Nov 2021. Do you still support only Application-monitoring on Bottlerocket AMI ? Did something change since then?

> 06:54:49 Installed version:
> 06:54:49 Using pre-packed installer, no download from external location will be performed.
> 06:54:49 ONEAGENT_INSTALLER_SCRIPT_URL=
> 06:54:49 ONEAGENT_INSTALLER_DOWNLOAD_TOKEN=
> 06:54:49 ONEAGENT_INSTALLER_DOWNLOAD_VERBOSE=
> 06:54:49 ONEAGENT_INSTALLER_SKIP_CERT_CHECK=
> 06:54:49 ONEAGENT_ENABLE_VOLUME_STORAGE=false
> 06:54:49 ONEAGENT_CONTAINER_STORAGE_PATH=
> 06:54:49 ONEAGENT_NO_REMOUNT_ROOT=
> 06:54:49 ONEAGENT_ADDITIONAL_UNMOUNT_PATTERN=
> 06:54:49 ONEAGENT_DISABLE_CONTAINER_INJECTION=
> 06:54:49 ONEAGENT_READ_ONLY_MODE=
> 06:54:49 AGENT_CONTAINER_IMAGE_VERSION=1.269.148.20230704-224319
> 06:54:49 Path: /usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 06:54:49 Started with capabilities: self: cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_sys_resource,cap_setfcap=ep
> 06:54:49 Started with user: uid=0(root) gid=0(root) groups=0(root)
> 06:54:49 Stored installation path as visible from host's mount namespace: /opt/dynatrace/oneagent
> 06:54:49 Stored data storage dir as visible from host's mount namespace: /var/lib/dynatrace/oneagent
> 06:54:49 Stored log dir as visible from host's mount namespace: /var/log/dynatrace/oneagent
> 06:54:49 Stored enrichment dir as visible from host's mount namespace: /var/lib/dynatrace/enrichment
> 06:54:49 Mounting basic directories
> 06:54:49 Bind mounting /mnt/root/x86_64-bottlerocket-linux-gnu/sys-root/usr/bin to /mnt/host_root/bin
> _**_06:54:49 Warning: Command '/usr/oneagentcapabilitieshelper mount --make-rslave /mnt/host_root/bin' failed, return code: 1, message: Error: mount failed, error code: 13, error message: Permission denied_**_
> 06:54:49 Error: Initialization procedure failed

**Comment by luhi-DT** [comment]
Hi, classicFullStack is not supported on Bottlerocket as stated in our [documentation](https://www.dynatrace.com/support/help/setup-and-configuration/technology-support#:~:text=x86%2D64-,Bottlerocket,-12)

However we still support applicationMonitoring without CSI Driver and with CSI Driver. Note in order to use the CSI Driver please follow: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-k8s/guides/networking-security-compliance/injection-readonly-volume


Thanks
Lukas
