### ISSUE TITLE
oneagent readiness probe fails and writes huge amount of logs 

### ISSUE THREAD

**Issue by shashank2300** [Dynatrace/dynatrace-operator#2052]
Oneagent readiness probe is failing and it shows below error:

  Warning  Unhealthy  31s                 kubelet  Readiness probe failed: grep: /proc/241348/stat: No such file or directory
grep: /proc/241379/stat: No such file or directory
grep: /proc/241383/stat: No such file or directory
grep: /proc/241389/stat: No such file or directory
  Warning  Unhealthy  13s  kubelet  Readiness probe failed: grep: /proc/242591/stat: No such file or directory
grep: /proc/242597/stat: No such file or directory
and as long as readiness probe is failing oneagent pods are writing a lot of logs to the VMs as a result filling the storage space on VMs. Snippet of logs in oneagent pods:
'/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_redhat-operators_90620(2).0.log' -> '/mnt/host_root/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_redhat-operators_90620(2).0.log' '/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_community-operators_bootstrap_26687.0.log' -> '/mnt/host_root/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_community-operators_bootstrap_26687.0.log' '/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_community-operators_bootstrap_26686(1).0.log' -> '/mnt/host_root/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_community-operators_bootstrap_26686(1).0.log' '/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_community-operators_26687.0.log' -> '/mnt/host_root/var/log/dynatrace/oneagent/go/ruxitagent_grpc_health_probe_community-operators_26687.0.log'

I'm using oneagent version 1.261.249 image. Operator version v0.12.1.

**Comment by chrismuellner** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
