### ISSUE TITLE
dynatrace-oneagent-csi-driver

### ISSUE THREAD

**Issue by shashank2300** [Dynatrace/dynatrace-operator#2053]
csi driver pods are crashing intermittently and containers restart many times. As mentioned in below events, Liveness probe fails in csi driver pods and the pod is going to CrashLoopBackoff state. This is observed in multiple clusters. After we restart these pods few times these are working fine. But this issue is seen very often.
```
 Warning  Unhealthy       93m (x8 over 94m)    kubelet            Liveness probe failed: Get "http://192.168.32.119:10090/livez": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Normal   Created         81m (x8 over 103m)   kubelet            Created container provisioner
  Normal   Pulling         76m (x11 over 106m)  kubelet            Pulling image "registry.connect.redhat.com/dynatrace/dynatrace-operator:v0.12.1"
  Warning  Unhealthy       41m (x58 over 94m)   kubelet            Liveness probe failed: Get "http://192.168.32.119:10080/livez": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy       11m (x4 over 52m)    kubelet            Liveness probe failed: Get "http://192.168.32.119:10090/livez": dial tcp 192.168.32.119:10090: connect: connection refused
  Warning  BackOff         65s (x401 over 93m)  kubelet            Back-off restarting failed container
```

Dynatrace Operator version used: 0.12.1

**Comment by chrismuellner** [comment]
Thank you for opening a Dynatrace Operator Issue. We've identified and tagged the issue as a "Support request".

Dynatrace responds to requests like these via [Dynatrace ONE support](https://support.dynatrace.com/) rather than Github. This helps our team respond as quickly as possible using the support team's tools and procedures.

Thanks for your help!
