### ISSUE TITLE
Feature request: Don't alert for scaled down nodes

### ISSUE THREAD

**Issue by cvdsande** [Dynatrace/dynatrace-operator#212]
I'm not sure if this already exists, but it would be nice if we didn't get "Host or monitoring unavailable" alerts for scaling down events.

An example alert:
<img width="642" alt="Screenshot 2021-08-06 at 13 51 27" src="https://user-images.githubusercontent.com/53912180/128513174-96087d90-007a-438e-aac7-9ee09711f003.png">

But it was for a normal scaling down event:
<img width="584" alt="Screenshot 2021-08-06 at 13 54 21" src="https://user-images.githubusercontent.com/53912180/128513428-cc5c5aa4-d4b5-4745-89fd-0925a5fe8a2c.png">

**Comment by DTMad** [comment]
The Operator already provides this functionality. If a node gets scaled down on purpose we send a mark for termination event to the Dynatrace cluster which prevents creating a problem for that specific host.

**Comment by cvdsande** [comment]
Ok, odd seems that didn't work in my case. I'll close this for now and open as a bug if the issue re-occurs.
