### ISSUE TITLE
Dynakube automatic kubernetes monitoring - Do not override environment settings

### ISSUE THREAD

**Issue by Forcebyte** [Dynatrace/dynatrace-operator#2149]
## Description

Today, we are attempting to migrate our Dynakube settings from a API setting within our Dynatrace tenant to a Activegate within the Dynatrace Operator, and are attempting to use 

The problem that appears to keep happening is that during a complete redeploy or recreation of the Dynakube namespace; the Dynatrace Operator will keep applying older invalid settings (for example, not monitoring PVCs or Metric Events) instead of defaulting to the Dynatrace Environment settings

## Notes

This appears to be a known limitation that the Dynatrace team does not want to persue within the Dynatrace Operator (see https://github.com/Dynatrace/dynatrace-operator/issues/884#issuecomment-1180074226) - which makes sense given the changes to the API being tied to the dynatrace-operator itself - however if the Dynatrace Operator is not intending to add such support, it should not override environment settings within a dynatrace tenant per cluster owned, as a redeployment of the cluster configuration will override environment specific (or script specific) settings within the environment

Due to above, the overall request we'd have is to have the Dynakube configuration _not_ override environment settings by default

**Comment by chrismuellner** [comment]
Since v0.13.0 of the Operator these settings or no longer overridden assuming the Dynatrace cluster version is 1.270+. The Kubernetes connection settings schema was updated to 3.0.0 which respects the hierarchical settings configured via other places.

If you are using a Dynatrace cluster with an older version this settings schema is not available and the old schema will be used as a fallback, leading to the behavior you have observed.

**Comment by Forcebyte** [comment]
Hi there, that probably is the case. Ill close this

I'm experiencing another issue with the newer Dynatrace version, but I'll file a separate issue since I think it's unrelated

Thanks!

**Comment by Forcebyte** [comment]
Thanks again @chrismuellner for the assist here; I've forked the new issue we're hitting with updates to https://github.com/Dynatrace/dynatrace-operator/issues/2185

I'll leave this one closed since looking at the Operator code this appears to be remediated in 0.13
