### ISSUE TITLE
Dynatrace Operator - Not granting the Dynatrace Operator access to image pulling and managing causes a hard-crash in v0.12.x+

### ISSUE THREAD

**Issue by Forcebyte** [Dynatrace/dynatrace-operator#2185]
**Describe the bug**
Crossposting the issue which as pointed out in the forms here: https://community.dynatrace.com/t5/Container-platforms/Error-after-update-dynatrace-operator-update/m-p/221587 since its causing our organization to not be able to update to 1.13 to remediate #2149 

![image](https://github.com/Dynatrace/dynatrace-operator/assets/44551053/46c95d45-a96d-4635-995a-e0cc763a9858)

In older versions of Dynatrace running on custom Kubernetes-based deployments using image registries that are privated (e.g. ACR or ECR) which use a custom method for authentication; the auto-upgrade that the Dynatrace Operator attempts to do would normally fail; since this isn't implemented, we accepted and managed the versioning of the operator, OneAgent, and Activegate manually - which works fine

In newer versions of Dynatrace - this hard-crashes during the reconcile
![image](https://github.com/Dynatrace/dynatrace-operator/assets/44551053/02da3a87-ecb8-43de-9fcf-14712bb692f7)

This was explained by a Dynatrace contributor, which reads:

> This error occurs because of a missing custom pull secret in the dynakube.
> 
> In older versions of the operator, this error was ignored, and reconciliation continued since we trusted the node to be set up correctly so the image would be pullable. This is not the desired behavior since the Operator does not know which version is actually rolled out and can therefore not prevent downgrade and provide other benefits. Since v0.11.0 the operator supports token-based authentication, whereas before, it was only possible to use username/password-based authentication.
> 
> Moreover, with v0.12.x+, the Operator check is improved and must have the same custom pull secret as is configured on the node.
> 
> To solve the problem, add a custom pull secret to Dynakube and reapply the dynakube.
> 

This normally wouldn't be an issue, and honestly would be a good change. But organizations which:
- disable password-only-authentication to docker registries, which is unsupported by the operator
- want to disable the auto-update functionality

This hard-breaks updates to the operator for 20+ clusters we currently utilize outside of OCP4 since we use the builtin registry.

**Expected behavior**

The Dynatrace Operator respects the AutoUpdate parameters, and does not attempt to reach out for auto updates detected via `oneAgent.autoUpdate` or other means.

**Comment by 0sewa0** [comment]
> disable password-only-authentication to docker registries, which is unsupported by the operator

AFAIK we support every kind of auth in the newer versions of the operator, could you elaborate ?

>  The Dynatrace Operator respects the AutoUpdate parameters, and does not attempt to reach out for auto updates detected via oneAgent.autoUpdate or other means.

How I understand it that you want that `autoUpdate: false` should cause that no communication is done with the registry, right?
- But that is not how it works: We communicate with the registry for the following reasons:
   - Get version of image (from an image label), mainly used for preventing downgrades and also for detecting upgrades
   - (In future versions) Get health-check of the oneagent to use it as liveness/readiness probe
   - (In future versions) Check if image is "immutable" (using a image label). Immutable images have to be handled a bit differently.
- In case `autoUpdate: false` the only thing that is different is that we do this once, to fill in the `Status` of the `DynaKube`.
   - If you updated from a version that does not have the new `Status` fields, then we will definitely communicate with the registry to fill out the `Status`. (the rest of the operator reads from the status what needs to be deployed)
- We got stricter about requiring communication with the registry because in the future we have to relay on it more, otherwise the operator would be "flying blind" and would deploy things that just don't work, and we want to avoid that.

**Comment by Forcebyte** [comment]
> > disable password-only-authentication to docker registries, which is unsupported by the operator
> 
> AFAIK we support every kind of auth in the newer versions of the operator, could you elaborate ?

For sure. Today the primary authentication flow we're using for pulling images down is Azure workload identity. Which is unique as the primary application is required to generate a temporary token to interact with the image container registry: https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview?tabs=dotnet

From what I can tell. Dynatrace operator only supports a static 'ImagePullSecret' which is not immutable


> > The Dynatrace Operator respects the AutoUpdate parameters, and does not attempt to reach out for auto updates detected via oneAgent.autoUpdate or other means.
> 
> How I understand it that you want that `autoUpdate: false` should cause that no communication is done with the registry, right?
> 
> * But that is not how it works: We communicate with the registry for the following reasons:
>   
>   * Get version of image (from an image label), mainly used for preventing downgrades and also for detecting upgrades
>   * (In future versions) Get health-check of the oneagent to use it as liveness/readiness probe
>   * (In future versions) Check if image is "immutable" (using a image label). Immutable images have to be handled a bit differently.
> * In case `autoUpdate: false` the only thing that is different is that we do this once, to fill in the `Status` of the `DynaKube`.
>   
>   * If you updated from a version that does not have the new `Status` fields, then we will definitely communicate with the registry to fill out the `Status`. (the rest of the operator reads from the `Status` what needs to be deployed)
> * We got stricter about requiring communication with the registry because in the future we have to relay on it more, otherwise the operator would be "flying blind" and would deploy things that just wouldn't work, and we have to avoid that.

Outside of the fact that you're relying on a image tag _way_ too much here to determine functionality; two primary points against that:
- If the Dynatrace oneagent needs to get the current version of the oneAgent in order to function, it would probably make more sense to fetch this from probing the one agents themselves. Since the image label that someone pushes to a container registry does not have the guarantee that it aligns with your versioning requirements
- Many other toolsets (for example Datadog or Gremlin) do not rely on reading the image version name from a container registry because of the point above. Instead it relies on either metadata endpoints that the daemonset exposes via HTTP/gRPC, or it treats the lifecycle as static and interoperable with the 'operator'

In addition giving an operator the ability to manage and pull down images at random to update deployments seems like a odd requirement that only Dynatrace appears to have. 

'Flying blind' seems to work fine with other open source projects, the older Oneagent Operator, and for people within the thread above using an older image of the operator - instead of that it appears that Dynatrace has a unique requirement to manage versioning for it's daemonset by requiring privileges to pull down and manage the lifecycle of its own daemonset outside of the operator model

If I were to make one plea here, it would be to not rely on a remote container registry that is not managed by Dynatrace (if the images are set in a custom manner) and either
- refer to the image version on the 'imageUrl' parameter directly if you _absolutely_ can't get this in another way
- have some sort of method to keep this check less verbose

As it stands it seems the only way I can monitor my kubernetes deployments using this operator is to give it privileges to pull down whatever image is in my private container registry, which is what I really want to avoid for both security and management reasons within the platform.

**Comment by chrismuellner** [comment]
We've made some changes that allow us to better ensure the prerequisites for communicating with the container registry are fulfilled. When `autoUpdate` is disabled, there is a single request per component per Dynakube that needs to work to ensure that the Dynatrace Operator is compatible with all components independent of their version.

**Comment by chcshinimai** [comment]
@chrismuellner 
So when `autoUpdate` is enabled, it won't check the compatibility? I am having the same issue with AWS ECR because of the change. This is blocking us from updating the dynatrace operator at the moment.
