### ISSUE TITLE
GKE Autopilot Mutating Webhook Namespace Selector

### ISSUE THREAD

**Issue by Dineshvcetster** [Dynatrace/dynatrace-operator#2194]
**Is your feature request related to a problem? Please describe.**
We use dynatrace-operator in our autopilot gke cluster and see some configurations out of sync in the mutating webhook.

Below configuration is automatically pushed and not in sync with the existing config.

namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - gke-gmp-system
            - gke-managed-cim

**Describe the solution you'd like**
Is there anyway we can parameterize it  namespace selector block

**Comment by chrismuellner** [comment]
It's not possible to modify system namespaces on GKE Autopilot, see [Built-in security configurations](https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security#built-in-security) for GKE Autopilot.

These modifications are automatically applied by Google and there is no way to opt-out of that. We do not recommend monitoring system namespaces and they are not monitored by default as well.

**Comment by Dineshvcetster** [comment]
@chrismuellner , my intention was not to modify the namespace.

Can we have something like this below in the mutating webhook configuration?


namespaceSelector:
matchExpressions: []

A placeholder for match expressions

**Comment by Dineshvcetster** [comment]
@chrismuellner , the below values are hard-coded in mutating webhook 

namespaceSelector:
      matchExpressions:
        - key: dynakube.internal.dynatrace.com/instance
          operator: Exists

But gke autopilot pushes below config and we were unable to override

matchExpressions:
- key: kubernetes.io/metadata.name
operator: NotIn
values:
- kube-system
- gke-gmp-system
- gke-managed-cim
