### ISSUE TITLE
Missing release notes for operator v0.14.0

### ISSUE THREAD

**Issue by mbrunn** [Dynatrace/dynatrace-operator#2241]
**Describe the bug**
There are no release notes for version 0.14.0 of the Dynatrace operator. Neither on the GitHub release page nor on the Dynatrace release notes page for the operator.

**To Reproduce**
1. Go to the [release page](https://github.com/Dynatrace/dynatrace-operator/releases) of the operator.
2. Click on "Release Notes can be found in our [official Documentation](https://www.dynatrace.com/support/help/whats-new/release-notes/dynatrace-operator)."
3. See that there are no release notes for v0.14.0

**Expected behavior**
I would expect to get the release notes for the operator v0.14.0 on the [GitHub releases page](https://github.com/Dynatrace/dynatrace-operator/releases/tag/v0.14.0) **AND** the [Dynatrace release note page](https://www.dynatrace.com/support/help/whats-new/release-notes/dynatrace-operator).

**Screenshots**
The following screenshot shows the state of the [release notes page on the Dynatrace documentation](https://www.dynatrace.com/support/help/whats-new/release-notes/dynatrace-operator) at the time of creating this issue.

![grafik](https://github.com/Dynatrace/dynatrace-operator/assets/83284692/9c935ec0-83fa-41c6-9e18-93bfa64d8723)

KR
Michael

**Comment by luhi-DT** [comment]
Hi, thanks for reaching out to us. Our internal docs team already published the release notes on our new documentation page here: https://docs.dynatrace.com/docs/whats-new/release-notes/dynatrace-operator/dto-fix-0-14-0 
There is currently a transition phase between new and old docs, I will also change the link on our release page. 

Thanks!
