### ISSUE TITLE
SkipCertCheck doens't work on Operator 14.x

### ISSUE THREAD

**Issue by YanDieg** [Dynatrace/dynatrace-operator#2396]
Hi,
As reported in this community post
https://community.dynatrace.com/t5/Container-platforms/Dynatrace-operator-0-14-0-or-0-14-1-issue/m-p/229308/highlight/true#M2046

Seems that the SkipCertCheck is ignored in Operator 14.x.

I tried also with 14.2 and i got the same issue.

**Comment by luhi-DT** [comment]
Hi, thanks for reaching out - we already fixed this with https://github.com/Dynatrace/dynatrace-operator/pull/2366 
This is going to be part of our 0.15.0 release, in general skipCertCheck is not a production grade setting, that should only be used for testing things. The way you solved it by actually providing valid certificates is the correct and secure way to work around this isse.
Thanks!
