### ISSUE TITLE
Can "useImmutableImage" be relaxed for pulling the OneAgent?

### ISSUE THREAD

**Issue by abh1kg** [Dynatrace/dynatrace-operator#249]
From what I could figure out, the _useImmutableImage_ flag is used to pull both the dynatrace operator and the oneagent images from a private Docker registry with an optional custom pull secret. I wonder if it makes sense to allow this optionally _only_ for the operator image and relax the constraint for the oneagent image.
If the useImmutableImage is not set, the operator tries to pull the image from Docker Hub - wouldn't it make sense to pull directly from the Dynatrace environment instead?

**Comment by DTMad** [comment]
The `useImmutableImage` field is not used for the dynatrace operator image but just for the OneAgent.
Here you can find additional information on the difference between the immutable and the lightweight image:
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/store-dynatrace-images-in-private-registries-kubernetes/#tabgroup-installer-modes--use-an-immutable-oneagent-image
