### ISSUE TITLE
dynatrace-routing serviceAccount missing deploying on OpenShift via OperatorHub

### ISSUE THREAD

**Issue by luigiaparicio** [Dynatrace/dynatrace-operator#261]
Installing via OperatorHub on OpenShift dynatrace-routing serviceAccount is not getting created

As a workaround I created manually and routing Pod starts running

**Comment by DTMad** [comment]
Hey @luigiaparicio,

you're right, thanks for bringing this to our attention.
We will will fix this for the next release and keep you updated.

**Comment by olljanat** [comment]
There looks to be similar/same issue with cloudNativeFullStack. Operator is constantly writing error like this to log:
```
{"level":"info","ts":"2021-11-30T09:02:44.100Z","logger":"controller_dynakube","msg":"Reconciling DynaKube","namespace":"dynatrace","name":"dynakube-cloud-native"}
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227","ts":"2021-11-30T08:46:04.100Z"}{"error":"Secret 'dynatrace:dynakube-cloud-native' not found","level":"error","logger":"controller.dynakube","msg":"Reconciler error","name":"dynakube-cloud-native","namespace":"dynatrace","reconciler group":"dynatrace.com","reconciler kind":"DynaKube","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:266
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
```

**Comment by luhi-DT** [comment]
Hi @olljanat, your issue looks like a different one, in your case, the secret dynakube-cloud-native you set in the CR.yaml with apiToken and Paas Token could not be found, therefor I would suggest to check if that secret exists in your cluster, because it needs to be generated manually
