### ISSUE TITLE
logs - log-level and json-format

### ISSUE THREAD

**Issue by AllroundIT** [Dynatrace/dynatrace-operator#2764]
We use a log server and it would be a great help if the log format was JSON. This would enable the log server to prepare the logs accordingly and they would be easier to read and find again.

In addition, in certain environments we are not interested in logs with the log level "debug" or "info", so it would be great if you could set the log level. This would also reduce the load on the log server, as the unnecessary logs would not arrive in the first place.

Currently, the "dynatrace operator" and "webhook" services already log out of the box in JSON format. 

Unfortunately, "active gate" and "one agent" do not.

**Comment by luhi-DT** [comment]
Hi @AllroundIT, thanks for your input, as you said operator/webhook/CSI Driver are already logging in json format. We are also working on different log levels and how we can utilise them best, however this repo is focused on the Dynatrace Operator and its components (webhook, csi driver) and not on OneAgent and ActiveGate, therefore please open an RFE (request for enhancement) in our Dynatrace community. This way we can ensure your input is not missed :) Thanks!
