### ISSUE TITLE
Duplicated resources in kubernetes.yaml of release 1.0.0

### ISSUE THREAD

**Issue by Fabian-K** [Dynatrace/dynatrace-operator#2931]
**Describe the bug**
The kubernetes.yaml of the 1.0.0 release contains duplicated resources. As an example, the PriorityClass dynatrace-high-priority is included twice (line 16 and line 6164). 

While this might be no issue when applying the file via `kubectl apply`, it is when using [kustomize](https://github.com/kubernetes-sigs/kustomize):

`accumulating resources from 'kubernetes.yaml': may not add resource with an already registered id: PriorityClass.v1.scheduling.k8s.io/dynatrace-high-priority.[noNs]`

Is it possible to remove the duplicated resources and make it compatible with kustomize?

Thanks, Fabian

**Comment by luhi-DT** [comment]
Hi @Fabian-K, thanks for the awesome finding, we have removed the duplicate resources and re-added the correct manifests now on the release. Sorry for this.

Thanks, Lukas!
