### ISSUE TITLE
Configure UpdateStrategy on CSI Driver

### ISSUE THREAD

**Issue by KevinThompsonYCRX** [Dynatrace/dynatrace-operator#2946]
**Is your feature request related to a problem? Please describe.**
In some very large clusters, it can take a very long time to roll out the CSI pods one-by-one during an update.

**Describe the solution you'd like**
Add a field `csidriver.updateStrategy.rollingUpdate.maxUnavailable` (or something more concise) to set the value for the daemonset

**Describe alternatives you've considered**
N/A, without being able to configure this to speed up the rollout, we are forced to either delete & recreate the whole DS, or raise the timeout on our helm releases to an unreasonable time range

**Additional context**
To be clear, this is the line I'd like to see variablized:
https://github.com/Dynatrace/dynatrace-operator/blob/v1.0.0/config/helm/chart/default/templates/Common/csi/daemonset.yaml#L283

**Comment by chrismuellner** [comment]
Thanks for the feature request!

We've created an internal ticket for it and will make this field configurable in the Helm chart in a future release.
