### ISSUE TITLE
Helm deployment on Kubernetes should support custom RootCAs to run non-JMX Extension 2.0 on the OneAgents

### ISSUE THREAD

**Issue by ericfortinsp** [Dynatrace/dynatrace-operator#3179]
**Is your feature request related to a problem? Please describe.**
Per Dynatrace [documentation](https://docs.dynatrace.com/docs/extend-dynatrace/extensions20/sign-extension#local-extensions), for non-JMX Extensions 2.0, we must upload our `root.pem` certificate into `/var/lib/dynatrace/oneagent/agent/config/certificates`.

- The OneAgent container on K8s doesn't use this path but most importantly, it seems there are no way to add the content on our `root.pem` file on our Values.yaml file and have it transported to the OneAgent pods.

**Describe the solution you'd like**
As a Helm user, I would like my OneAgents pods running on K8s to use my `root.pem` content that I've provided in my `values.yaml` file when I've installed the Dyntrace-operator Helm chart on my Kubernetes cluster.
That way, I could run non-JMX Extension 2.0 on my cluster.

**Describe alternatives you've considered**
None as it seems the OneAgent are deployed by the dynatrace-operator (outside my control)

**Comment by chrismuellner** [comment]
You can configure the certificates using the `trustedCAs` field in the Dynakube: [Network configuration guide in official documentation](https://docs.dynatrace.com/docs/shortlink/network-restricted-environments#trusted-ca-certificate)

**Comment by ericfortinsp** [comment]
Hello Christoph, thanks for the reply.  Unfortunately, it doesn't seem to be the setting needed for my use case.   I didn add my custom root.ca per the documentation you provided but as soon as the config was pushed onto Kubernetes, these errors appeared in the logs:

```
error making post request to dynatrace api: Post "https://<url masked>/e/<env masked>/api/v1/tokens/lookup": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

That error makes sense since I've instructed the dynatrace-operator to communicate to my Dynatrace environment with a new trustedCA and my Dynatrace environment **hasn't** been started with that new custom rootCA.  This is where I think there was a misunderstanding.  My use case is in regard to Extensions 2.0 **code signing** certificates.

Per [this Dynatrace documentation](https://docs.dynatrace.com/docs/shortlink/sign-extension#upload):
- Each host running your extension, whether OneAgent or ActiveGate, needs to have the root certificate saved in a dedicated directory.

> That `root certificate` is the one added to the [Dynatrace Credential Vault](https://docs.dynatrace.com/docs/shortlink/sign-extension#add-cert) and it is used for **Extension validation** only (not for SSL communication between the K8s server agents and the Dynatrace server)

Let me know if more information is needed, 
Thank you
