### ISSUE TITLE
Add annotations and labels to deployments

### ISSUE THREAD

**Issue by amirasyraf** [Dynatrace/dynatrace-operator#3182]
**Is your feature request related to a problem? Please describe.**
Currently it is possible to set annotations and labels to pods by overriding the values as seen here https://github.com/Dynatrace/dynatrace-operator/blob/v1.0.1/config/helm/chart/default/values.yaml

But this only adds annotations/labels to the pods, not the deployments.

**Describe the solution you'd like**
Add ability to propagate annotations/labelsto deployments and pods, if possible to be controlled independently

**Describe alternatives you've considered**
Possibly Kyverno but it would be better if this is natively supported

**Comment by chrismuellner** [comment]
Current behavior is that labels and annotations that are set for Operator/Webhook/CSI Driver are both set for pods, but only labels are set for Deployments/Daemonset.

We'll fix this in a future release and set annotations for the Deployments/Daemonsets as well!
