### ISSUE TITLE
CRD release files contain non-CRDs

### ISSUE THREAD

**Issue by halovanic** [Dynatrace/dynatrace-operator#3215]
Starting with the 1.0.0 RC series, the generated CRD download on GitHub now contains most, if not all other resources like a PriorityClass, CSIDriver, Daemonset, etc. which are in conflict with the main helm chart.

I can work around this by manually stripping it of everything but the CustomResourceDefinitions, otherwise an upgrade, such as stated here is problematic: https://docs.dynatrace.com/docs/setup-and-configuration/setup-on-k8s/guides/operation/update-uninstall-operator#expand--upgrade-from-a-dynatrace-operator-version-less-0-8-0--2

**Comment by luhi-DT** [comment]
Hi, thanks for the finding and the hint -> this was due to a problem in our Release process. I exchanged all the CRDs with the correct version and opened a PR to correct the error.

Thanks,
Lukas!
