### ISSUE TITLE
Inconsistent mountpoints in CSI driver since 1.20

### ISSUE THREAD

**Issue by halovanic** [Dynatrace/dynatrace-operator#3533]
0a3f2d21897243f921d905dc5dcd0b38fefab233 modified the logic for the mount point inconsistently, leaving the provisioner controller still referencing the API URL with a TODO comment.

This caused all pods to fail initialization after upgrading to 1.20 (and 1.21) under the CSI driver as I had the API URL set to the "friendly" domain name, such as "https://friendly.live.dynatrace.com/api" instead of the form with the tenant ID like "https://yXYZ.live.dynatrace.com/api".  The webhook ends up trying to mount a path not created by the CSI driver and fails initialization indefinitely.

Even if the operator code **had** been updated consistently, I suspect it may have still led to some in-place upgrade timing problems for users due to the driver mountpoint path being altered.  It seems like there might have been an assumption that the API URL had always been of tenant ID form and this change would not have any noticeable effects.

**Comment by yul14nrc** [comment]
@halovanic @gkrenn I am deploying the dynatrace operator 1.2.1 using the kubernetes observability and application observability, all the pods inside the dynatrace namespace are running and the dynakube CRD also is in running state, but when I restarted the application pods those failing to start with the following messages:

`Unable to attach or mount volumes: unmounted volumes=[oneagent-bin], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition

MountVolume.SetUp failed for volume "oneagent-bin" : rpc error: code = Unknown desc = record not found`

This issue maybe is causing this kind of errors?

**Comment by chrismuellner** [comment]
Resolved in v1.2.2!
