### ISSUE TITLE
expose failurePolicy in values .yaml

### ISSUE THREAD

**Issue by Aimen618** [Dynatrace/dynatrace-operator#3535]
**Is your feature request related to a problem? Please describe.**
the following parameter failurePolicy is hardcoded to ignore and it will be useful if we make it configurable:
webhooks:
  - name: webhook.pod.dynatrace.com
    reinvocationPolicy: IfNeeded
    failurePolicy: Ignore

**Describe the solution you'd like**
change it to:
{{.Values.webhook.mutatingWebhook.failurePolicy}}

**Describe alternatives you've considered**
manual patching after the chart deployment

**Additional context**
link to code:
https://github.com/Dynatrace/dynatrace-operator/blob/v1.1.0/config/helm/chart/default/templates/Common/webhook/mutatingwebhookconfiguration.yaml#L25

**Comment by chrismuellner** [comment]
This has the implication that a failure in the webhook or problems with the webhook deployment, in general, would block the rollout of any pods that are expected to be monitored. We have added many features to reduce the impact of failure in any of our monitoring components on the general cluster. Still, we can make this setting configurable.

We'll add this in a future release of the Operator.
