### ISSUE TITLE
 Endpoints "dynatrace-webhook" not found for new 1.2.X deployments

### ISSUE THREAD

**Issue by reespozzi** [Dynatrace/dynatrace-operator#3542]
**Describe the bug**
Please tell me if there's something obvious I'm missing but upgrading to latest version does not seem as straightforward / without breaking changes as the docs suggest

We are using flux to automate our helm install of dynatrace-operator and dynatrace-crds. The kustomization for dynatrace-crds goes into a ready state and crds are installed, but for dynatrace-operator it fails with this message:

```
DynaKube/dynatrace/dynakube dry-run failed: conversion webhook for dynatrace.com/v1beta1, Kind=DynaKube failed: Post "https://dynatrace-webhook.dynatrace.svc:443/convert?timeout=30s": endpoints "dynatrace-webhook" not found
```

CRD is fine with a stored version of v1beta2.

**To Reproduce**
1. Fresh helm install of 1.2.1 with latest CRDs
2. Updated dynakube file to use new apiVersion v1beta2 and all that entails
3. See error?

**Expected behavior**
Upgrading to v1beta2 dynakube should work when upgrading to 1.2.1, but in a fresh install via flux seems blocked by no conversion webhook being found

**Additional context**
I saw a suggestion online to remove this conversion strategy:
```
Spec:
  Conversion:
    Strategy:  Webhook
    Webhook:
      Client Config:
        Service:
          Name:       dynatrace-webhook
          Namespace:  dynatrace
          Path:       /convert
          Port:       443
      Conversion Review Versions:
        v1
        v1beta1
```

And set it to nothing, but for a fresh install there is no existing webhook to convert. I tried this anyway and it caused everything to get stuck 

In our case, with no installation of dynatrace available, the svc it's looking for:
```
Service:
          Name:       dynatrace-webhook
          Namespace:  dynatrace
          Path:       /convert
          Port:       443
```
is not being found each time. I also tried a straight forward apply of a generic svc named dynatrace-webhook in that namespace, but that didn't seem to work (because there's no pods deployed yet for the svc to talk to)

I also think you should make clearer in your docs what's classed as a breaking change, https://docs.dynatrace.com/docs/whats-new/release-notes/dynatrace-operator/dto-fix-1-2-0 `standalone metadata enrichment` for instance, when not included during an upgrade caused a JSON schema error and failure to install.. In that case it doesn't seem like a feature or enhancement but a breaking change

**Comment by Whisper40** [comment]
Same error while upgrading from 1.1.0 to 1.3.2 with FluxCD
Same error with fresh install.

`Helm install failed for release dynatrace/dynatrace with chart kubernative-dynatrace@1.3.2-dev-6695938: Unable to continue with install: could not get information about the resource DynaKube "dynakube" in namespace "dynatrace": conversion webhook for dynatrace.com/v1beta1, Kind=DynaKube failed: Post "https://dynatrace-webhook.dynatrace.svc:443/convert?timeout=30s": service "dynatrace-webhook" not found`

**Comment by Whisper40** [comment]
@reespozzi Hello, do you found a solution with FluxCD ?

**Comment by reespozzi** [comment]
@Whisper40 In the end yes, this charming solution:

`delete the HR wait for it to come up and fail, then delete the crds` -- seem to remember having to do this a few times though and it's really not ideal if your deployment is critical

**Comment by reespozzi** [comment]
If you have dynatrace support, maybe worth going through there to get this raised and fixed upstream, as it seems a standard approach to close off a genuine issue...

**Comment by reespozzi** [comment]
@chrismuellner can this be reopened please? It seems 90% of issues raised here are just auto-closed as support requests.. This is still happening for us going to 1.4.X as well

**Comment by ciaranca** [comment]
@chrismuellner are you able to reopen this issue to be investigated?
