### ISSUE TITLE
Drop all capabilities for csi-driver containers

### ISSUE THREAD

**Issue by dennis-ge** [Dynatrace/dynatrace-operator#3639]
**Is your feature request related to a problem? Please describe.**
Hi, I was wondering why the csi-driver in the helm chart is not dropping all capabilities by default?
i.e., 
```yaml
csidriver:
  securityContext:
   ...
    capabilities:
      drop:
        - ALL
```

According to https://docs.dynatrace.com/docs/setup-and-configuration/setup-on-k8s/reference/security#dynatrace-csi-driver, it doesn't require any capabilities (contrary to OneAgent).

**Describe the solution you'd like**
It would be possible to add this to the helm chart by default.

**Describe alternatives you've considered**
I configured my helm chart (which builds upon this one) to drop all capabilities for all csidriver containers and everything looks good (pods are healthy and no suspicious logs).

**Additional context**
This is rather a question than a feature request. I can also provide a PR to add the option to the helm chart if requested.

**Comment by chrismuellner** [comment]
The permissions in the [Dynatrace CSI driver permission list](https://docs.dynatrace.com/docs/shortlink/security#dynatrace-csi-driver) are only related to RBAC resources, i.e. everything related to working with the Kubernetes API, not linux capabilities.

Capabilities for the CSI driver are required when it is used to provide volumes to either Host agents or injected applications. ([How it works](https://docs.dynatrace.com/docs/shortlink/how-it-works-k8s#csi-driver))
