### ISSUE TITLE
OOTB excluded namespaces not publicly documented

### ISSUE THREAD

**Issue by axelayala1988** [Dynatrace/dynatrace-operator#3728]
**Is your feature request related to a problem? Please describe.**
I am currently working with Scotiabank and they have been trying to implement the CNFS operator as a standard for observability across their k8s clusters. They have had several challenges with this deployment, as they have found some things that are not publicly documented and faced challenges due to this.
One thing that they noted is lack of observability for certain workloads that are critical to them. They noted that the documentation specified that there are 3 namespaces where the OneAgent isnt injected into, **kube-, openshift-** and the namespace where Dynatrace is installed. Still, there were other workloads that were excluded from monitoring.
Doing some reverse engineering, they found out a snippet which clearly indicates that there are 2 more namespaces that have been excluded OOTB from monitoring that are not documented, **gke- and gmp-.**
![image](https://github.com/user-attachments/assets/aa15c0b7-de12-4109-8e61-ce1fb9cd8bac)

**Describe the solution you'd like**
It would be very helpful to add these namespaces to the public documentation to ensure that customers understand and expect lack of visibility into these kind of workloads OOTB, instead of having to learn it the hard way or having to reverse engineering it as Scotiabank did.

**Describe alternatives you've considered**
Not sure if there is a better way of notifying about this and include this information in the public documentation.

**Additional context**
This is the snippet they found and used to confirm the reason why they werent seeing the data they were expecting. Already talked with Michael Rynkiewicz and he suggested opening this issue.
![image](https://github.com/user-attachments/assets/db2d2cd3-8b2f-4299-a499-4f1b3685ebe1)

**Comment by chrismuellner** [comment]
It's already documented in our official documentation that some namespaces are excluded: https://docs.dynatrace.com/docs/shortlink/annotate

**Comment by d41k4n** [comment]
The gke-* and gmp-* prefixed namespaces are not mentioned as exceptions in the official docs. FWIW I've already submitted feedback to the doc team about that.
