### ISSUE TITLE
Dynatrace Operator 0.3.0 incorrect reference

### ISSUE THREAD

**Issue by KennyBrea** [Dynatrace/dynatrace-operator#377]
https://github.com/Dynatrace/dynatrace-operator/releases/latest/download/openshift3.11.yaml 

This config references  v1beta1 but installs the 0.2.2 image from redhat where only v1alpha1 exists, anyone installing the operator on 3.11 will encounter this issue and be unable to rectify without updating line 2987.

**Comment by DTMad** [comment]
Hey @KennyBrea,

this is correct. The version 0.3.0 does not exist yet and therefore it links to the openshift3.11.yaml of version 0.2.2 where the latest version of the CRD was v1alpha1 still.
