### ISSUE TITLE
url not found

### ISSUE THREAD

**Issue by ccfly2018** [Dynatrace/dynatrace-operator#39]
![image](https://user-images.githubusercontent.com/34997234/100883996-ecd0d500-34eb-11eb-8212-4a66033dc9d9.png)
https://github.com/Dynatrace/dynatrace-operator/releases/latest/download/kubernetes.yaml  can not be used, please refresh it

**Comment by DTMad** [comment]
Hey @ccfly2018,

This operator hasn't been released yet - therefor the file does not exist.
It will be released soon - so stay tuned ;)

Quote from the README.md:
Note: this project is currently in development. Shouldn't be installed by customers yet.

Thanks,
Marco

**Comment by ccfly2018** [comment]
OK, thanks. In k8s cluster, install activeGate should log in linux machine ? Can I install by deployment?

**Comment by DTMad** [comment]
Hey,
sorry what do you mean by:
"In k8s cluster, install activeGate should login linux machine according wget?"

Can I install by deployment?
Yes. From next week on there will be documentation on how to deploy it as a StatefulSet or via the Dynatrace Operator.
