### ISSUE TITLE
Update default page w/ helm chart, and simplify the install steps and summary of what the operator does

### ISSUE THREAD

**Issue by lknite** [Dynatrace/dynatrace-operator#3938]
### Is your feature request related to a problem? Please describe.
When I google 'github helm chart dynatrace' I end up on a [page with older helm charts](https://github.com/Dynatrace/helm-charts).  The page links to this [page](https://github.com/Dynatrace/dynatrace-operator), where there isn't a helm chart.

Generally, with every application I've ever deployed to kubernetes one can google 'github helm chart \<application\>' and end up at a github page where it provides the commands to add the helm chart repo to helm, or it provides a command to show the latest oci helm chart.  Here's a [basic example.](https://github.com/MoJo2600/pihole-kubernetes)

This page provides a giant manifest file which someone can use to install dynatrace, this seems to be the focus, but of course that strategy doesn't work as well with updates.  Helm charts are designed to be installed and updated.

Through the dynatrace gui I can see a helm chart:
```
- name: dynatrace-operator
  version: 1.2.2
  repository: oci://public.ecr.aws/dynatrace
```

This seems to be the answer but the documentation is lacking.  For example, right now, try to google 'dynatrace helm chart' and see if you end up with documentation on that helm chart.

### Describe the solution you'd like
I'm still working to get things installed but I think what is needed on this [page](https://github.com/Dynatrace/dynatrace-operator) is:

Summary:
dynatrace-operator manages DynaKube resources.

To get started:
1. install the dynatrace-operator
2. create a dynakube resource file
3. provide apiToken and dataInjectToken used by dynakube resource file

Installing dynatrace-operator
- install the manifest file (useful for testing)
- install using the helm chart (use for production)
  - helm install dynatrace-operator oci://public.ecr.aws/dynatrace/dynatrace-operator

Create a dynakube resource file
- this file is what the dynatrace-operator manages, a basic template can be found here: [dynakube.yaml]()
- before the dynakube resource will work, you will need to provide the apiToken and dataInjectToken

Provide secrets needed by dynakube
- create a secret named 'dynatrace' in the namespace where the dynatrace operator is installed 'dynatrace-operator' with two keys:
  -  apiToken
  -  dataIngestToken

### Describe alternatives you've considered
The large manifest install file method is discouraging to someone looking for a helm chart, as they will immediately go back to google looking for the helm chart, this takes people away from this main page and the explanation that the operator is managing the dynakube resource.  The only location where the helm chart url can be located seems to be via screenshots someone took of the dynatrace website install page.  ... and once you find the helm chart there is no explanation that the 'Dynakube' resource is needed ... so you install the operator and nothing happens.

### Additional context
Part of the reason for the difficulty encountered is that I don't have access to the dynatrace website, my coworker does, this caused me to google for the helm chart in the usual way.  It may be that few people end up doing this, but those who take the time should have a good experience also.

**Comment by lknite** [comment]
Here's a message I just sent in a ticket I had with dynatrace:
```
Ok, so here’s what I learned, and what future customers will be looking for:

Summary:
- dynatrace-operator manages dynakube resources
- the name of the dynakube resource is the name which appears in the dynatrace gui

Setup is:
1. Install dynatrace-operator using helm chart
     - oci://public.ecr.aws/dynatrace/dynatrace-operator
2. Deploy dynakube resource
     - set ‘name’ of resource to the value you want to see in Dynatrace gui
     - set ‘oneAgent.cloudNativeFullStack.args’ host-group --set-host-group={{.Values.hostgroup}}
3. Create secret needed by dynakube resource with apiToken and dataIngestToken

This ticket can be closed.
```

I think what's happening is the documentation is focused on a single person installing to a single cluster.  With just a few more details customers will have a good experience more quickly deploying to multiple clusters.

**Comment by chrismuellner** [comment]
Documentation is located in the official Dynatrace documentation, e.g. instructions on how to deploy the Operator are in [Kubernetes Deployment](https://docs.dynatrace.com/docs/setup-and-configuration/setup-on-k8s/installation)!

The readme on Github is not intended to be used in production. If you need more assistance please reach out to our Support!
