### ISSUE TITLE
oneagent image not part of dyntrace operator mirroring

### ISSUE THREAD

**Issue by sullyvon** [Dynatrace/dynatrace-operator#3964]
**Describe the bug**
oneagent image not part of dyntrace operator mirroring

We are mirroring redhat certified dynatrace operator but oneagent is not part of it.

We have pull and push in directly, ok workaround but seems like this image should be part of the olm image set

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by luhi-DT** [comment]
Operator and OneAgent are two seperate components, the operator can also be configured in modes that are not deploying the OneAgent, therefore the Dynatrace Operator and the OneAgent are not bundled and published together
