### ISSUE TITLE
ActiveGate Install In K8s Cluster

### ISSUE THREAD

**Issue by ccfly2018** [Dynatrace/dynatrace-operator#40]
In K8s Cluster, should I install ActiveGate by wget like this https://www.dynatrace.com/support/help/setup-and-configuration/dynatrace-activegate/installation/install-an-environment-activegate/?install-on-windows%3C-%3Einstall-on-linux=install-on-linux. Can you give us a deployment for k8s ?

**Comment by DTMad** [comment]
Hey @ccfly2018 ,

There is no containerised ActiveGate yet.
It will be released with Dynatrace Cluster version 1.207.

This will be released next week and furthermore the Dynatrace Operator will be officially released then.
Please stay tuned until next week.

There will then also be official documentation on how to use this.

May I ask for the expected use case?

Thanks,
Marco

**Comment by ccfly2018** [comment]
Thanks， expect for Dynatrace Cluster version 1.207.
