### ISSUE TITLE
Missing cr.yaml for release 0.3.0

### ISSUE THREAD

**Issue by lucadentella** [Dynatrace/dynatrace-operator#405]
Hi

following the guide on the official website:
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/openshift/store-dynatrace-images-in-private-registries-openshift/#tabgroup-installer-modes--use-an-immutable-oneagent-image

you are supposed to download cr.yaml with:
`curl -Lo cr.yaml https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.3.0/cr.yaml`

but it's missing

**Comment by luhi-DT** [comment]
Hi, we have added the cr.yaml and the link you posted above to download the cr is also valid now.
