### ISSUE TITLE
Lightweight OneAgent image does not start

### ISSUE THREAD

**Issue by halovanic** [Dynatrace/dynatrace-operator#406]
Following the [Private Registries Instructions](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/store-dynatrace-images-in-private-registries-kubernetes/#tabgroup-installer-modes--use-a-lightweight-oneagent-image) for a lightweight image, the Docker Hub image given at docker.io/dynatrace/oneagent:latest does not start for a Dynatrace Managed environment when set via the classic full stack monitoring CR, giving this startup error:

> 01:39:57 Bootstrapping regular deployment
01:39:57 Started agent deployment as a container, PID 15738.
01:39:57 System version: Linux ec2amaz-*redacted* 5.4.156-83.273.amzn2.x86_64 #1 SMP Sat Oct 30 12:59:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
01:39:57 Command line: --set-host-property=OperatorVersion=v0.3.0 --set-deployment-metadata=orchestration_tech=Operator-classic_fullstack --set-deployment-metadata=script_version=v0.3.0 --set-deployment-metadata=orchestrator_id=*REDACTED* --set-host-id-source=auto
01:39:57 Installed version:
01:39:57 ONEAGENT_INSTALLER_SCRIPT_URL=
01:39:57 ONEAGENT_INSTALLER_DOWNLOAD_TOKEN=
01:39:57 ONEAGENT_INSTALLER_DOWNLOAD_VERBOSE=
01:39:57 ONEAGENT_INSTALLER_SKIP_CERT_CHECK=
01:39:57 ONEAGENT_ENABLE_VOLUME_STORAGE=
01:39:57 ONEAGENT_CONTAINER_STORAGE_PATH=
01:39:57 ONEAGENT_NO_REMOUNT_ROOT=
01:39:57 ONEAGENT_ADDITIONAL_UNMOUNT_PATTERN=
01:39:57 ONEAGENT_DISABLE_CONTAINER_INJECTION=
01:39:57 ONEAGENT_READ_ONLY_MODE=
01:39:57 AGENT_CONTAINER_IMAGE_VERSION=1.229.65.20211018-111427
01:39:57 Path: /usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
01:39:57 Started with capabilities: Capabilities for `self': = cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_sys_resource,cap_setfcap+eip
01:39:57 Started with user: uid=0(root) gid=0(root) groups=0(root)
01:39:57 Error: The ONEAGENT_INSTALLER_SCRIPT_URL environment variable must be initialized with your cluster's agent download location (to be obtained via "Deploy Dynatrace" in the Dynatrace UI). Example:
01:39:57 If you are not sure how to launch the container please visit: https://www.dynatrace.com/support/help/shortlink/oneagent-docker
01:39:57 Error: Initialization procedure failed

The default Dynatrace environment-hosted OneAgent image (or a private-hosted version of it per the "immutable" directions) works as expected.  If this particular option has been intentionally superseded by the new monitoring modes, then the private registries documentation likely needs updating.

**Comment by ntt2k** [comment]
Any update on this issue? I run into the same issue!

**Comment by meik99** [comment]
The documentation has been updated to reflect that the Operator does not support a lightweight OneAgent image:
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/other-configuration-options/store-dynatrace-images-in-private-registries-kubernetes#lightweight-mode
