### ISSUE TITLE
Installing via Helm to custom namespace conflicts with CRD since 0.3.0

### ISSUE THREAD

**Issue by jkayani** [Dynatrace/dynatrace-operator#411]
The `dynatrace-operator` Helm chart lets you install to a custom namespace, including deploying all the webhook configuration to the specified namespace: https://github.com/Dynatrace/helm-charts/tree/dynatrace-operator-v0.3.0/dynatrace-operator/chart/default/templates/Common/webhook

The CRD however hardcodes the expected namespace of the webhook to `dynatrace`: https://github.com/Dynatrace/dynatrace-operator/blob/master/config/crd/patches/webhook_in_dynakubes.yaml#L13. This causes the update to that version of the operator to fail. 

I understand the CRD and the chart are decoupled but it may be worth documenting that this is a possible problem. Our solution is to deploy the CRD alongside the operator with our own Helm chart and modify the offending line to say `{{.Release.Namespace}}` instead.

**Comment by chrismuellner** [comment]
Thanks for pointing this out.

For now, if you download the [CRD from the latest release](https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.3.0/dynatrace.com_dynakubes.yaml), it has this patch applied already and you could just replace the namespace with a different value.
