### ISSUE TITLE
A PDB is created even though highAvailable is set to false.

### ISSUE THREAD

**Issue by chcshinimai** [Dynatrace/dynatrace-operator#4112]
**Describe the bug**
With version 1.3.x when you deploy the helm chart with highavailability: false, it still creates a PDB for dynatrace-webhook pod. This cause it never gets evicted when kubernetes upgrade for example. 

**To Reproduce**
helm template with `highAvailability: false`

**Expected behavior**
When highAvailable is set to false, pdb shouldn't be created.

**Comment by chrismuellner** [comment]
Fixed in #4013, will be available in v1.4.0
