### ISSUE TITLE
dynakube-classic pods getting error "Insufficient access rights (drwxr-x---) on: /var/log" on openshoft

### ISSUE THREAD

**Issue by vknemanavar** [Dynatrace/dynatrace-operator#418]
04:09:29 Error: Insufficient access rights (drwxr-x---) on: /var/log
04:09:29 Error: /var/log path must be globally traversable (--x permissions for others).
04:09:29 Error: Please adjust the permissions and then retry the installation.

**Comment by DTMad** [comment]
Hey @vknemanavar,
Do you run on GKE with COS?
Could you please try to enable volume storage?
See https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring#expand--anthos-and-gke--4

**Comment by vknemanavar** [comment]
Hi @DTMad ,

We are running on IBM Cloud (ROKS), we are not using any storage i believe it is ephemeral storage.

**Comment by vknemanavar** [comment]
Hi @DTMad 
How enable volume storage will help?, if we put ONEAGENT_CONTAINER_STORAGE_PATH to /opt --> what exactly store in /opt?

**Comment by tony-advent** [comment]
I have just come across this same issue, I have asked for the online manuals to be updated, copy the "Additional configuration for Anthos, SUSE CaaS, GKE, IKS, and TKGI"  section under Container Platform/Kubernetes/Set up monitoring to Container Platform/OpenShift/Set up monitoring

**Comment by luhi-DT** [comment]
Hi @tony-advent, did the instructions from @DTMad fix your issue ? Thanks!

**Comment by tony-advent** [comment]
Hi @luhi-DT the issue was fixed by reading the Kubernetes Section in the manuals, My request twas to update the OpenShift Section with the same information.

**Comment by luhi-DT** [comment]
Thanks for pointing that out, I will forward it :)

**Comment by dbellagio** [comment]
Hi @luhi-DT , I know this issue is a bit old, but I am seeing this exact same problem after following install directions from Dynatrace. What exactly is the fix to this problem?

**Comment by dbellagio** [comment]
Just to provide a solution to this issue that someone can find, it appears through trial and error we set these envs in the env section of the dynakube yaml:

ONEAGENT_CONTAINER_STORAGE_PATH = /opt
ENABLE_VOLUME_STORAGE = true
