### ISSUE TITLE
Version 0.3.0 missing from Operatorhub catalog in Openshift

### ISSUE THREAD

**Issue by faandg** [Dynatrace/dynatrace-operator#434]
### What did you do?
 Updating the Dynatrace operator to 0.3.0 does not seem to be possible using the operatorhub available in OpenShift. It's the same experience when looking up the operator on operatorhub.io: https://operatorhub.io/operator/dynatrace-operator

### What did you expect to see? 
The Dynatrace operator should be available to be updated using the means available in openshift.
 
### Environment
 * OpenShift version information (if applicable):
openshift 4.7.31

**Comment by luhi-DT** [comment]
Hi, we are aware of that and we are currently working on the release of the Operator to RedHat Catalogs.

**Comment by chrismuellner** [comment]
Version 0.4.1 should be available in the Openshift Operatorhub now

**Comment by LDL-GH** [comment]
@chrismuellner the operator seems to be available on Openshift Operatorhub.
operatorhub.io only shows 0.2.2?
