### ISSUE TITLE
oneagent Daemonset pods interfering with aws-vpc-cni node startup

### ISSUE THREAD

**Issue by gazal-k** [Dynatrace/dynatrace-operator#449]
We have `dynatrace-operator` running in our EKS clusters using the helm chart: https://github.com/Dynatrace/helm-charts/tree/master/dynatrace-operator/chart/default

Recently, when we updated the aws-vpc-cni addon, we noticed that it wasn't able to startup. The reason seemed to be an injected dynatrace library.

```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  26s               default-scheduler  Successfully assigned kube-system/aws-node-587pv to ip-*-*-*-*.ap-southeast-2.compute.internal
  Normal   Pulled     25s               kubelet            Container image "602401143452.dkr.ecr.ap-southeast-2.amazonaws.com/amazon-k8s-cni-init:v1.9.3" already present on machine
  Normal   Created    25s               kubelet            Created container aws-vpc-cni-init
  Normal   Started    25s               kubelet            Started container aws-vpc-cni-init
  Normal   Pulled     24s               kubelet            Container image "602401143452.dkr.ecr.ap-southeast-2.amazonaws.com/amazon-k8s-cni:v1.9.3" already present on machine
  Normal   Created    24s               kubelet            Created container aws-node
  Normal   Started    24s               kubelet            Started container aws-node
  Warning  Unhealthy  4s (x2 over 14s)  kubelet            Readiness probe failed: /app/grpc-health-probe: symbol lookup error: /opt/dynatrace/oneagent/agent/bin/current/linux-x86-64/liboneagentproc.so: undefined symbol: __environ
```
We had to do the following steps to workaround this issue:
- Uninstall `dynatrace-operator`
- Delete the oneagent daemonset (because that doesn't happen as part of operator uninstallation)
- Wait for the aws-vpc-cni Daemonset to progress
- Reinstall dynatrace-operator

This does not manifest for new nodes, because aws-node Pods start (and has to) before any other Pods including oneagent Pods. This only manifests when we update the cni Daemonset.

**Versions:**
EKS: 1.20
dynatrace-operator: 0.3.0
OneAgent: 1.231.245

**Comment by gazal-k** [comment]
Sorry, yes, you are right. It is a oneagent issue and not specifically an operator issue. I imagine oneagent is not hosted on GitHub though. We do have a support ticket open with the same details.

About uninstalling the operator, the document you provided is for operator installed using vanilla k8s manifest (`kubectl apply/delete -f`). However, we manage it using `helm`. And the mechanism we know of about uninstalling applications using helm is: `helm uninstall dynatrace-operator`. We have also noticed that updates to the helm chart recreates activegate StatefulSet and oneagent Daemonset. I'll create a separate issue for that though.

**Comment by gazal-k** [comment]
Issue for unexpected chart update and uninstall behaviour: https://github.com/Dynatrace/helm-charts/issues/172

**Comment by gazal-k** [comment]
> We saw this issue as well, we were able to come to another solution that might be useful. If you go into the dashboard and tell dynatrace not to monitor the namespace of aws-node-* pods, then it will not try to inject on launch of the pods.

Yup, that's the recommendation we got from dynatrace support and that worked for us too

**Comment by JKrehling** [comment]
Note for anyone finding this. 
Please update your oneagent to v1.237.110 or greater.

**Comment by manas-biswal-cr** [comment]
also happening for dynatrace:1.47.1001
