### ISSUE TITLE
Custom Resource - metdata name

### ISSUE THREAD

**Issue by tony-advent** [Dynatrace/dynatrace-operator#463]
I have copied the example Custom Resource, While applying the CR's on OpenShift the 'metadata: name:' must be dynakube.
If you change the name, the CR will not create the DaemonSets.
This was discovered while trying to deploy the multiDynakube.yaml, the metdata/name have  dynakube-application-monitoring and dynakube-cloud-native. If you apply the CR, nothing happens.
I applied cloudNativeFullStack.yaml, DaemonSet is created. Change the metadata/name to dynatrace-full, nothing happens, no DaemonSet or additional Pods. (dynakube-oneagent)

**Comment by chrismuellner** [comment]
Use the `spec.tokens` field (described in the samples) if the Secret containing the tokens has a different name than the Dynakube.
