### ISSUE TITLE
skipCertCheck: false

### ISSUE THREAD

**Issue by lagunary** [Dynatrace/dynatrace-operator#464]
Hello Guys,

We have faced with a problem regarding docker registry certificate.
Our setup is the Dynatrace cluster (as well as it docker registry) is protected with self-sign CA (internal CA).
The skipCertCheck flag is affecting only the dynatrace server and not affecting with docker registry (sometimes called insecure registry).
We cannot  (and we dont want to) modify your docker image and there is no way to get this activegate image (oneagent images can be pulled from dockerhub, or from openshift). 
Workaround is to manually pulled from dynatrace registry and push to another private docker registry which is not protected with internalCA issued certificate.
Another workaround to use managed dynatrace dns but imho this is not a good solution.

Please extend your image to be able to use "insecure" (internal CA issued tls protected) registry.

Thanks in advance.
Viktor

**Comment by luhi-DT** [comment]
Hi, you have the possibility to add a trusted Certificate via `trustedCAs: name-of-my-ca-configmap` in the CR.yaml. The certificate has to be available in a config map in the namespace of the Operator. If there are anymore questions, feel free to open a issue.

**Comment by lagunary** [comment]
Yes, Ive tried it for sure. Ive made configmap and data contains certs: | CERTIFICATES. But I  have same error.
