### ISSUE TITLE
Comment in sample CR is incorrect

### ISSUE THREAD

**Issue by LucasHocker** [Dynatrace/dynatrace-operator#465]
In dynatrace-operator/config/samples/hostMonitoring.yaml, the image section lists the default image source as docker hub. In discussion with container team, it's actually pulled from cluster instead. The comment should be updated to reflect this.

**Comment by luhi-DT** [comment]
Hi, thanks for the hint, we already updated the samples on master branch and for the new release version https://github.com/Dynatrace/dynatrace-operator/pull/491
