### ISSUE TITLE
invalid capability=metrics-ingest on classicFullStack

### ISSUE THREAD

**Issue by collinjlesko** [Dynatrace/dynatrace-operator#478]
Hello,

In file: `dynatrace-operator/config/samples/classicFullStack.yaml`

The below `- metrics-ingest` is an invalid parameter. According to docs only possible values are the top two.
```
  # Configuration for ActiveGate instances.
  activeGate:
    # Enables listed ActiveGate capabilities
    capabilities:
      - routing
      - kubernetes-monitoring
      - metrics-ingest
```

After removing the last parameter, the file applies perfectly with `kubectl apply -f "<name of yaml>"`

To reproduce: follow standard docs [here](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring#config).

Let me know if I am doing something wrong here, which is entirely possible 😄 .

Thanks!

**Comment by chrismuellner** [comment]
The samples in the documentation incorrectly reference the samples on master which are using unreleased features.
The link will be updated to reference the samples for the latest release.

**Comment by luhi-DT** [comment]
Hi, the link [here](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring#config) has been updated to use the latest release, instead of master. This issue should therefore be fixed. Thanks for your patience :)
