### ISSUE TITLE
Auto discovery of dashboards/alert rules/ other configurations by the dynatrace operator

### ISSUE THREAD

**Issue by gowrisankar22** [Dynatrace/dynatrace-operator#500]
Hi All,

Grafana dashboards are automatically discovered from the ConfigMaps in the deployed namespace. If a ConfigMap has been created with the `grafana_dashboard` label set to "1" , then the JSON encoded dashboard in the ConfigMap will be imported into Grafana. 

Same way, if the dynatrace operator detects and auto imports automatically based on certain label, will ease our life for the automation. 

Are there any plans to support this feature ?

**Comment by luhi-DT** [comment]
Hi, this is currently not supported and also not planned. I will take that the responsible Project Manger to follow that idea up.
