### ISSUE TITLE
Remove "dynatrace" namespace naming requirement

### ISSUE THREAD

**Issue by d41k4n** [Dynatrace/dynatrace-operator#510]
The current documentation and associated deployment manifests should not assume it's always possible to deploy the operator into a namespace called "dynatrace" on the target cluster.

Some users (especially larger enterprises) are running their workloads in fully managed multi-tenant K8s/OpenShift PaaS clusters which may enforce strict naming rules for namespaces.

In our case we had to do a search & replace of any occurrences of the string "namespace: dynatrace" in the [openshift.yaml](https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.4.0/openshift.yaml) manifest before applying it.

While this is relatively simple and seems to do the trick I think at least the documentation should be improved in this regard.

**Comment by chrismuellner** [comment]
If you use the release manifests directly (e.g. `kubernetes.yaml`) we have this requirement on a specific namespace.

When using the helm chart you can install the operator to any namespace.
