### ISSUE TITLE
Operator version for OC 3.11

### ISSUE THREAD

**Issue by dannemca-kyndryl** [Dynatrace/dynatrace-operator#511]
Hi team good day. As per https://github.com/Dynatrace/dynatrace-operator#supported-platforms the proper Operator Version for the Openshift 3.11 should be the v0.2.2. But when prompt for the install command on the "Deploy Dynatrace" page, we get the same install.sh for the Kubernetes, with no flag like the "--openshift". This way we are always getting the latest version instead of the v.0.2.2 and the installation fails at some point due to incompatible commands/actions.
Please let me know how do I proper select the v.0.2.2 on the "Deploy Dynatrace" page, or even the proper install.sh for the v.0.2.2, since even there it is still pointing to a 404 file: https://github.com/Dynatrace/dynatrace-operator/releases/latest/download/openshift3.11.yaml ([line 108](https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.2.2/install.sh)) .
Thanks.

**Comment by dannemca-kyndryl** [comment]
Updating the correct v.0.2.2 install.sh : https://github.com/Dynatrace/dynatrace-operator/releases/v.0.2.2/install.sh

**Comment by meik99** [comment]
When using the Deploy Dynatrace page, select the Openshift tab. Below the textbox containing the installation commands you will find a note that reads `For Openshift 3.11 or lower you need to manually set up Dynatrace Operator v0.2.2. See [installation instructions on GitHub](https://dt-url.net/ab02wkl?dt=s&u=e).` The link will point you to the 0.2.2 GitHub release containing the correct files.
