### ISSUE TITLE
No install plan generated for upgrade from 0.2.2 to 0.4.1

### ISSUE THREAD

**Issue by LDL-GH** [Dynatrace/dynatrace-operator#535]
# Bug Report
## What did you do?
Updating the Dynatrace operator to 0.4.1 does not seem to be possible using the operatorhub available in OpenShift.

Since #434 has been resolved I've tried to update the dynatrace operator from 0.2.2 to 0.4.1 however there does not seem to be an available upgrade path. The subscription does not seem to generate a new install plan.
Restarting the dynatrace-operator pod did not make a difference.

![image](https://user-images.githubusercontent.com/81672459/152331669-72a06a9c-13bb-4e52-8665-5640ad5ca272.png)
![image](https://user-images.githubusercontent.com/81672459/152331742-f0bb7ec7-82ab-4e03-8d3a-43952babb379.png)

## What did you expect to see?
An install plan being generated to update the operator to the latest available version.

## Environment
OpenShift version information (if applicable):
openshift 4.8.27

**Comment by luhi-DT** [comment]
Hi, as the installMode of our Operator changed from "OwnNamespace" to "AllNamespaces", you have to uninstall the old version and install the new one. Unfortunately RedHat does not support automatic updates of Operators incase the install Mode changes.
