### ISSUE TITLE
Synthetic-enabled ActiveGates

### ISSUE THREAD

**Issue by Fabian-K** [Dynatrace/dynatrace-operator#550]
Hi,

is it possible to deploy & manage a 'Synthetic-enabled ActiveGate' with the operator? The ActiveGate should be used for private synthetic location monitoring.

Thanks,
Fabian

https://www.dynatrace.com/support/help/how-to-use-dynatrace/synthetic-monitoring/private-synthetic-locations/system-and-hardware-requirements-for-private-synthetic

**Comment by chrismuellner** [comment]
Not yet, will probably be added in the future.
