### ISSUE TITLE
[Feature Request] - Add ability to create custom-named clusters when 'automatic-kubernetes-api-monitoring' is set

### ISSUE THREAD

**Issue by Forcebyte** [Dynatrace/dynatrace-operator#564]
# Problem Statement

At the moment, when 'automatic-kubernetes-api-monitoring' is set, Kubernetes integration appears to automatically take the same name as the Dynatrace object

I'm mostly inferring that from here: https://github.com/Dynatrace/dynatrace-operator/blob/290b87df16f0e77d1653c1072d608e1c059eb1a8/src/controllers/dynakube/dynakube_controller.go#L342
```go
		err := automaticapimonitoring.NewReconciler(dtc, dynakubeState.Instance.Name, dynakubeState.Instance.Status.KubeSystemUUID).
			Reconcile()
```

This is normally fine, but when dealing with multiple clusters (or multiple 'kinds' of clusters, maybe one per region or something) its very confusing to see the default 'Dynakube' integration name most of the time

# Request / Enhancement

It'd be nice to have some sort of configuration in the `dynakube.yaml` file to specify a specific cluster configuration... or even just use the cluster name by default instead of `dynakube` - ideally that would solve most(?) of the naming conveniton issues that I see sometimes when registering a cluster

**Comment by JKrehling** [comment]
https://github.com/Dynatrace/dynatrace-operator/blob/master/config/samples/classicFullStack.yaml

apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace


If the name is dynakube so is everything else. 
If you change this to 

apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube-krehling
  namespace: dynatrace

Everything should get that name

**Comment by Forcebyte** [comment]
Hey @JKrehling, thanks for the reply back!

We're aware, I think I have that somewhere in the original req
> At the moment, when 'automatic-kubernetes-api-monitoring' is set, Kubernetes integration appears to automatically take the same name as the Dynatrace object

the problem is twofold I guess
- we'd have to have manual kustomize configurations _per cluster_ that replicate the name of the dynakube object to match the name of the cluster
- the naming of the dynakubev1 object across clusters would be different, which would come through in OPAL CRD reports we have as 'breaking naming convention'

In reality this issue kinda meshes with #510 in a way -  if you're a large-scale K8s user then having to deal with name mapping instead of having a method to define it via a parameter (similar to how you'd define the ApiURL) or something is a bit of an annoyance


Don't get me wrong, renaming the dynakubev1 object works in the interim for a single cluster, but It'd be nice if it could be standardized in a better way from the points above

**Comment by JKrehling** [comment]
I think the reasoning was that k8s cluster don't really know their own name. 
https://github.com/kubernetes/kubernetes/issues/44954

There are some names people give cluster, or the name that kubeadm will give when you install but not a name the api returns. 
 export NAME=`kubectl config view -ojsonpath={.clusters[0].name}`;envsubst < cr-dynatrace-managed-csi.yaml | kubectl apply -f -

**Comment by Forcebyte** [comment]
> I think the reasoning was that k8s cluster don't really know their own name. [kubernetes/kubernetes#44954](https://github.com/kubernetes/kubernetes/issues/44954)
> 
> There are some names people give cluster, or the name that kubeadm will give when you install but not a name the api returns. export NAME=`kubectl config view -ojsonpath={.clusters[0].name}`;envsubst < cr-dynatrace-managed-csi.yaml | kubectl apply -f -

yeah that's fair, from an autodiscovery perspective there's additional searching that a good chunk of monitoring agents do to obtain that though (k8s politics aside, completely agree with you on that point😄)

For example (I hate to bring up a different vendor, just giving an example of what we've seen done before), Datadog earmarks a bunch of conditional checks in the event that it can't find a name or has an issue with the name
```go
		// autodiscover clustername through k8s providers' API
		if data.clusterName == "" {
			for cloudProvider, getClusterNameFunc := range ProviderCatalog {
				log.Debugf("Trying to auto discover the cluster name from the %s API...", cloudProvider)
				clusterName, err := getClusterNameFunc(ctx)
				if err != nil {
					log.Debugf("Unable to auto discover the cluster name from the %s API: %s", cloudProvider, err)
					// try the next cloud provider
					continue
				}
				// if the clustername is valid but contains a "_" in the middle of it, we will replace it later such that
				// to make it valid to RFC1123.
				if clusterName != "" {
					log.Infof("Using cluster name %s auto discovered from the %s API", clusterName, cloudProvider)
					if strings.HasSuffix(clusterName, "-") || strings.HasSuffix(clusterName, "_") {
						log.Errorf("Registering an invalid clusterName as they are not allowed to end with `_` or `-`")
					}
					data.clusterName = clusterName
					break
				}
			}
		}

		if data.clusterName == "" {
			clusterName, err := hostinfo.GetNodeClusterNameLabel(ctx)
			if err != nil {
				log.Debugf("Unable to auto discover the cluster name from node label : %s", err)
			} else {
				data.clusterName = clusterName
			}
		}

		if data.clusterName != "" {
			if lower := strings.ToLower(data.clusterName); lower != data.clusterName {
				log.Infof("Putting cluster name %q in lowercase, became: %q", data.clusterName, lower)
				data.clusterName = lower
			}
		}
```

via this mutex https://github.com/DataDog/datadog-agent/blob/c337ac0dbc97ad7714c6b8e5ed22f5a382a7ee29/pkg/util/kubernetes/clustername/clustername.go#L68

Kube-state, and other vendors also obtain it via Annotation, that could also work
```
Selector:           strimzi.io/cluster=my-cluster,strimzi.io/kind=Kafka,strimzi.io/name=my-cluster-kafka
Labels:             app.kubernetes.io/instance=my-cluster
                    app.kubernetes.io/managed-by=strimzi-cluster-operator
                    app.kubernetes.io/name=kafka
                    app.kubernetes.io/part-of=strimzi-my-cluster
                    strimzi.io/cluster=my-cluster
                    strimzi.io/kind=Kafka
                    strimzi.io/name=my-cluster-kafka
```

(dummy value, but same thing applies, kube-state's integration checks an annotation instead of hardcoding)

**Comment by chrismuellner** [comment]
With `v0.7.0` you can do this by setting an additional feature flag on the dynakube:
```yaml
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/automatic-kubernetes-api-monitoring: "true"
    feature.dynatrace.com/automatic-kubernetes-api-monitoring-cluster-name: "<your-cluster-name>"
spec:
...
```

This will also be added to the official documentation soon.

**Comment by Forcebyte** [comment]
Thank you @chrismuellner! Functionality is working perfectly

I can open another feature request for this if needed, but as an aside is there a method to set specific kubernetes monitoring options as part of the annotation?

Screenshot attached for an example of those configurations - we deploy to many clusters so having these not have to be managed and imported by a separate script or automation would be ideal:
![example2](https://user-images.githubusercontent.com/44551053/176959363-9f887938-97a0-4500-abdf-467b1fb6b641.jpg)
