### ISSUE TITLE
Webhooks prevent any pods from being created in an OpenShift cluster

### ISSUE THREAD

**Issue by sipe90** [Dynatrace/dynatrace-operator#576]
I upgraded Dynatrace operator from version 0.2.2 to version 0.4.2 on OpenShift 4.9 from OperatorHub. The operator and webhook deployments were created in the `openshift-operators` namespace. After a while, all new pods in the whole cluster fail to be created with an error: `admission webhook "webhook.pod.dynatrace.com" denied the request: no DynaKube instance set for namespace: <namespace>`. And this is even before the DynaKube resource is created.

And even after creating the DynaKube the problem still persists. I'm assuming this is because we use classic full-stack monitoring since the cloud-native full-stack monitoring is still not recommended to be used in production and I believe this webhook is supposed to work with that.

Am I doing something wrong here? Or is there an issue with the webhooks since to me they don't seem to work properly?

**Comment by luhi-DT** [comment]
Hi, we had an issue with the 0.4.2 release on OperatorHub, therefore we reverted the version released on OperatorHub back to 0.2.2, which should work again. Sorry for the inconvenience and a newer working version will follow soon.

**Comment by luhi-DT** [comment]
Hi, we released 0.5.0 on operatorHub yesterday and the issues should be resolved :) Therefore I will close this issue. Thanks for your patience.
