### ISSUE TITLE
operator 0.4.2 via operatorHub does not work

### ISSUE THREAD

**Issue by LDL-GH** [Dynatrace/dynatrace-operator#581]
When trying to install 0.4.2 the operator does not roll out any oneagent & activegate pods.
There are no error messages in the logs of the dyntrace-operator or dynatrace-webhook pods.

Installing 0.4.2 via oc apply does seem to work but is not preferred.
Main difference that I found was that using oc apply the operator pods are scheduled in the dynatrace namespace as before.
While using operatorHub these pods are scheduled in the openshift-operator namespace.

OpenShift version information (if applicable):
openshift 4.8.27

**Comment by luhi-DT** [comment]
Hi, we released 0.5.0 on operatorHub yesterday and the issues should be resolved :) Therefore I will close this issue. Thanks for your patience.

**Comment by LDL-GH** [comment]
@luhi-DT  I've installed 0.5.0 today and the problem seems to persist.

I install the operator, it's installed in openshift-operators with AllNamespaces (no other option)
I create a namespace openshift-monitoring-dynatrace (tried dynatrace as well)
I create a dynakube secret containing necessary tokens in this namespace
And finally I create the dynakube in the namespace.

Unfortunately no oneagent/activegate pods are created

**Comment by MKInv** [comment]
I have the exactly same problem with 0.5.0. I also tried openshift-monitoring and dynatrace namespace. No pods are started.
