### ISSUE TITLE
Difference in behavior between Ubuntu and Bottlerocket based Kube Nodes

### ISSUE THREAD

**Issue by vinay01tech** [Dynatrace/dynatrace-operator#605]
Hi Team,

We have found following difference while moving Kubernetes nodes form Ubuntu to Bottlerocket based ami:

1. Not able to run as Daemonset only Deployment is running because of this Dynatrace inject sidecar init-container to all the application pods.
2. With Ubuntu based nodes, they are treated as single host for monitoring on dynatrace and for Bottlerocket based nodes dynatrace inject sidecar container to each pods, which treated pod as a single host, we observe this in most of the pods.

Want to know why this difference in behavior with Bottlerocket ami as well how to run Dynatrace as Daemonset into k8s nodes based on Bottlerocket ami ?

Kuberenets: AWS-EKS 1.21

**Comment by luhi-DT** [comment]
Hi, did you use the same CR.yaml on both platforms? If so can you please post it here in order to check what deployment mode you used. Thanks!

**Comment by luhi-DT** [comment]
Hi, did you use the same CR.yaml on both platforms? If so can you please post it here in order to check what deployment mode you used. Thanks!

**Comment by vinay01tech** [comment]
Any update on this ?
