### ISSUE TITLE
Support 'ImageName' for OneAgent+ActiveGate in CloudNativeFullStack

### ISSUE THREAD

**Issue by Forcebyte** [Dynatrace/dynatrace-operator#607]
## Problem Statement

At the moment, we have the following container configuration using the previous `dynatrace-oneagent-operator`

![image](https://user-images.githubusercontent.com/44551053/156222956-c73c00c3-4284-4030-9405-0b5f8b6a22a4.png)

this works for what we need to do, and makes it so we dont have to have any publically exposed endpoints within our cluster in EKS

Newer versions of the `CloudNativeFullStack` dynakube object do not have the ability to configure a OneAgent or activegate from an image URL under spec.activegate or spec.oneagent; it'd be ideal if we had the ability to specify this

Otherwise, we have to directly connect to the SaaS activegate (note the arrow on the right) - which adds a network flow we ideally do not want to have for an entirely private cluster

![image](https://user-images.githubusercontent.com/44551053/156223320-9ac9a8af-6954-4bca-9798-0b3103593431.png)

**Comment by baichinger** [comment]
Hi! ActiveGate does have an image field: https://github.com/Dynatrace/dynatrace-operator/blob/v0.4.2/src/api/v1beta1/activegate_types.go#L73-L75

For OneAgent there is currently none and it would not fully solve your requirement anyways. CloudNativeFullStack uses the CSI driver which manages the lifecycle of code modules. It therefore downloads archives from the server.

**Comment by Forcebyte** [comment]
Hey @baichinger, thanks for the reply back! You're right, it probably wouldn't solve the 100% private usecase that was laid out above; I'm mostly referring to the OneAgent spec here, from what I can tell (at least from first glance) the CSI driver would redirect queries to the APIUrl, so it would technically still be private if we were able to proxy the calls to either the containerized activegate or to a separate activegate specified in the APIUrl.

The main issue from our perspective is if that APIUrl were to be a private ActiveGate used to do all of this, managed systems such as EKS or AKS using pre-defined managed nodes would reject the private-facing TLS certificate that whatever activegate I have deployed would utilize (cause we'd be pulling the OneAgent image at the docker layer, the custom certificate configmap would not apply here) - The CSI Driver downloading archives from the server would probably use the ConfigMap custom TLS cert as specified in the documentation,

I guess to be succinct here, I think our main overarching issue with this design is probably the fact that there is no way to integrate native K8s monitoring with an image using a centralized repository store, it is fairly anti-pattern to expect managed cloud-based solutions (E.g. EKS or AKS) in the `CloudNativeFullStack` template to use non cloud-native image repositories and instead hope that 
- the Dynatrace SaaS/Managed tenants that customers use which the operator does this pulling from on the ValidationWebhook are always up
- the image store would be a non-centralized repository (I'm using GKE, AKS, and EKS within my work environment, and in all situations all vendors allow us to pull down and specify images in a CRD fashion

Just on our basis alone tools like AquaSec or other image-repository scanning tools that any enterprise uses would probably have to exempt the image store that is used for the OneAgent

With above i'm not 100% sure that removing the private requirement for an image spec, but it would probably be the best interim solution given the stuff laid out in the previous comment

Let me know if above adds any context here

**Comment by mreider** [comment]
Hi @Forcebyte.

Here's the plan:

- We will provide instructions, and a Dockerfile, for creating your own code module images.
- We will offer **image** key/value pairs to the CloudNativeFullStack settings for host agents and code modules.

This solves your problem by allowing you to store activegates, oneagents, and code modules in your own container registries. The CSI pod will pull these images and offer them as mounts to other pods. You would be responsible for providing API url's and to them as usual.

We are forecasting this work for this quarter - meaning we are working on it now in Q2. Hopefully it will be finished around the June timeframe.

Thanks

- Matt

**Comment by davcen** [comment]
Hi! I've a similar issue in my case:
- Azure Kubernetes Service (AKS)
- all workloads pull the relevant images from a private Azure Container Registry (ACR) for security compliance forced by the customer
- dynatrace-operatore deployed in "CloudNativeFullStack" through Helm Chart
- use of private images following the official documentation [Store Dynatrace images in private registries in Kubernetes
](https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/store-dynatrace-images-in-private-registries-kubernetes#lightweight-mode)
- the "dynakube-oneagent" DaemonSet uses a "live" image, pulled from <ENVIRONMENT_ID>.live.dynatrace.com/linux/oneagent:latest (the other pods related to Dynatrace are ok, pointing to the private repos provided in the custom Helm values file)

I would like to pull an image from a private repo also for the pods of this daemonset.

I hope this issue will be addressed as soon as possible :-)

Thanks for your great work!

**Comment by misjackal** [comment]
Hi, 

@mreider - Can you support "imageName" for application-only mode with CSI driver too ?
We would like to use such option.

Thanks in advance.

**Comment by chrismuellner** [comment]
With `v0.7.0` we now support image fields for activegate, host agent and code modules for all deployment modes. See [official parameter list](https://www.dynatrace.com/support/help/shortlink/dto-params-k8s#native) for list of options.

**Comment by Forcebyte** [comment]
This works well, thank you @chrismuellner 

Silly side question, if its okay to ask:

for images within Kubelet, we usually use Service Principal MSI Auth to authenticate to the downstream container registry (see https://docs.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli)

when we attempt to utilize `codeModulesImage` as part of that parameter list, we get a `unauthorized: authentication required` error back from within the CSIDriver Daemonset, is there a proposed feature to allow for any sort of MSI or AWS IAM Authentication to upstream image providers?
