### ISSUE TITLE
[Question] Support for Prometheus Endpoint scraping

### ISSUE THREAD

**Issue by TimGerlach** [Dynatrace/dynatrace-operator#64]
Hi Team,
we were wondering if this dynatrace-operator also targets to take over scraping of own Prometheus endpoints on the Kubernetes cluster at some point in time?

**Comment by mmayr-at** [comment]
Hi @TimGerlach,
can you elaborate on this use case a bit? Do I understand it correctly, that you want to use the operator to configure scraping of custom prometheus endpoints within the Kubernetes cluster instead of our current approach we have described [in our docs](https://www.dynatrace.com/support/help/technology-support/cloud-platforms/kubernetes/monitoring/monitor-prometheus-metrics/).

**Comment by TimGerlach** [comment]
If I understand it correctly, the dynatrace-operator cannot scrape Prometheus metrics of my annotated endpoints, but only takes care of the standard Kubernetes metrics which means I would need to deploy a second ActiveGate for Prometheus scraping. Or is the dynatrace-operator already able to scrape my Prometheus endpoints, too?

**Comment by mmayr-at** [comment]
Yes, you are correct - Prometheus scraping is done by the ActiveGate and not by the Dynatrace Operator. However the Dynatrace Operator deploys an ActiveGate for Kubernetes monitoring and this one capable of Prometheus scraping, when you deploy a `DynaKube` custom resource as described [here](https://github.com/Dynatrace/dynatrace-operator#create-dynakube-custom-resource-for-activegate-rollout). So it is already possible :) Does this answer your question?

**Comment by TimGerlach** [comment]
Oh, got it. That's cool!

To be honest, from the README it appears that only the Kubernetes API is scraped by the ActiveGate deployed by the dynatrace-operator and scraping of other Prometheus endpoints wouldn't be supported (yet):

> As of launch, the Dynatrace Operator can be used to deploy a containerized ActiveGate for Kubernetes API monitoring. New capabilities will be added to the Dynatrace Operator over time [...]

Also the `DynaKube` example manifest doesn't indicate that Prometheus monitoring is supported (in fact the mentioned link to  [./deploy/cr.yaml](https://raw.githubusercontent.com/Dynatrace/dynatrace-operator/master/deploy/cr.yaml) seems to be broken).

**Comment by lrgar** [comment]
> in fact the mentioned link to ./deploy/cr.yaml seems to be broken
Thanks for letting us know, I've fixed the links.

As for Prometheus support, I think it's considered to just be part of our Kubernetes integration, and perhaps that's the confusion.

**Comment by TimGerlach** [comment]
Thanks for the clarification and the quick fix.

From experience with a couple of development teams, I think the README would benefit from mentioning the Prometheus integration explicitly to avoid confusion.
