### ISSUE TITLE
[Feature Request] Add ability to allow set annotations within helm values

### ISSUE THREAD

**Issue by edogden-pbx** [Dynatrace/dynatrace-operator#649]
At the moment it's not possible to set custom annotations in the custom resource DynaKube template with helm values.
The use case I'm after is so I can set `feature.dynatrace.com/automatic-kubernetes-api-monitoring` to `true` defined by the helm values rather than doing this manually.

REF: https://github.com/Dynatrace/dynatrace-operator/blob/df84aed153f11165eef57ad7f2cab4d8b15cec51/config/helm/chart/default/templates/Common/customresource-dynakube.yaml#L21

**Comment by chrismuellner** [comment]
WIth `v0.7.0` you have to define the CR separately and apply it after the helm chart is installed, so you can customize the whole CR to you needs.
