### ISSUE TITLE
Upgrading dynatrace-operator from v0.2.2 to 0.5.0

### ISSUE THREAD

**Issue by geremy42** [Dynatrace/dynatrace-operator#663]
I'm trying to upgrade dynatrace-operator from v0.2.2 to 0.5.0 on my AKS cluster.

When launching install.sh script, I sometimes get following errors:
`Wait for webhook to become available`
`pod/dynatrace-webhook-xxb7ccbb54-hpjt4 condition met`
`error: timed out waiting for the condition on pods/dynatrace-webhook-xx657fdfb-g6vdv`

Sometimes it's working but I still get errors on readiness probe of dynatrace-webhook pod:
`Readiness probe failed: Get "https://<endpoint_ip>:8443/healthz": dial tcp <endpoint_ip>:8443: connect: connection refused`

Once deployed, it seems not having any impact on data export as I'm able to see metrics/information on Dynatrace portal

Subsidiary question: Is-it possible to avoid using dynatrace-webhook ? I want to work on ClassicFullStack mode

**Comment by luhi-DT** [comment]
Hi @geremy42, no this is not possible, as the Webhook also executes different tasks, which are need for all modes. (e.g validating your cr.yaml or converting an old DynaKube to a new one)
