### ISSUE TITLE
Kubernetes workloads not apearing with dynatrace operator 0.5.0

### ISSUE THREAD

**Issue by jeanluclariviere** [Dynatrace/dynatrace-operator#675]
I'm trying to deploy the Dynatrace operator 0.5.0 to an RKE1 cluster using the recommended classic full-stack CR. Following the latest steps provided here I perform the following:

1. Create dynatrace namespace
2. Create secret with API tokens (1 for api, 1 for ingest)
3. Apply the kubernetes.yaml file. (I've had to comment out the seccompProfile because our PSPs don't like these)
4. Update the classicFullStack.yaml with our apiUrl
5. Apply the classicFullStack.yaml

Everything appears to come up:
```
NAME                                  READY   STATUS    RESTARTS   AGE
dynakube-activegate-0                 1/1     Running   0          3m35s
dynakube-oneagent-gzwwc               1/1     Running   0          3m35s
dynakube-oneagent-rv94g               1/1     Running   0          3m35s
dynatrace-operator-74745c468f-q9g4z   1/1     Running   0          4m52s
dynatrace-webhook-7c964ffdcf-bkn2f    1/1     Running   0          4m52s
```

I can also see the activegate is present:
![image](https://user-images.githubusercontent.com/11167646/160532142-ada0e025-f1d6-4271-967b-6fdc0a228c8b.png)

Checking the hosts, I can see the worker nodes are there, indicating the OneAgents are doing their job.

However, if I check under **Infrastructure** > **Kubernetes**, the cluster isn't listed.

**Comment by jeanluclariviere** [comment]
Finally got this working. Dynakube was complaining about insufficient privileges. After adding settings.read and settings.write to the API token everything came up as expected.

```
Message: Token on secret dynatrace:dynakube missing scopes [settings.read, settings.write]
Reason: TokenScopeMissing
```

I believe we should amend the documentation to include the settings read/write:


> Make sure the tokens have the following permissions:
> 
> API Token
> Read Configuration
> Write Configuration
> Read Entities (if using automatic kubernetes api monitoring)
> Installer Download
> Access problem and event feed, metrics and topology
> Data Ingest Token
> Ingest Metrics

**Comment by luhi-DT** [comment]
Hi, the official documentation already reflects, that you need settings.read and settings.write here: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring#prerequisites
