### ISSUE TITLE
Troubleshooting script exited with code28

### ISSUE THREAD

**Issue by vigneshsolution** [Dynatrace/dynatrace-operator#677]
Hi all,

We are running AKS 1.22.2 cluster where we have deployed Dynatrace components(dynatrace-operator, oneagent, activegate etc) using helm installation method under "dynatrace-acc" namespace. 
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/set-up-k8s-monitoring-with-helm

Tried to validate the installation process using the below script.
https://github.Com/dynatrace/dynatrace-operator/tree/master/troubleshoot

While we ran the troubleshooting script against "dynatrace-acc" namespace, getting error(attached in this case), could someone assist on this.

Using
Kubectl 1.22
AKS cluster 1.22.2
Dynatrace operator 0.4.2

Thanks in advance
![dynatrace-acc troubleshooting error](https://user-images.githubusercontent.com/35495686/160551358-eba8379f-cf0b-4f72-a30f-560c76c9b046.png)

**Comment by luhi-DT** [comment]
Hi, the step you failed at is a curl command, which means `OPERATION_TIMEOUTED`. Is your installation working, or do you experience any problems?

**Comment by vigneshsolution** [comment]
@luhi-DT 

Sorry for the delay in response, Installation for partially done, couple of pods are having some issues(CSI driver pod). Attaching the screenshot. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/35495686/162944682-e1b1c8f7-6009-45bb-b134-760c92d674e7.png)

**Comment by luhi-DT** [comment]
Hi, great to hear that it works for you with the latest release. Which troubleshoot script are you using? Because in an older version there was a bug included, where the activeGate Image check was wrong.

**Comment by vigneshsolution** [comment]
Hi, Below is the URL we are referring to. Could you please direct us to latest script.

https://github.com/dynatrace/dynatrace-operator/tree/master/troubleshoot

**Comment by meik99** [comment]
Can you confirm that the image `activegate:latest` exists in your `azurecr.io` registry and that the pull secret contains the correct credentials for it?
