### ISSUE TITLE
Remove invalid dynatrace-api capability from samples/classicFullStack.yaml

### ISSUE THREAD

**Issue by costco-kynelson** [Dynatrace/dynatrace-operator#724]
dynatrace-api is not a valid capability when we tested on Dynatrace Operator v0.5.1 on OpenShift.

https://github.com/Dynatrace/dynatrace-operator/blob/f9bae7a5cb59895bf02be80495f59f6611b81799/config/samples/classicFullStack.yaml#L119

https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/openshift/set-up-ocp-monitoring#parameters

capabilities	Defines what the ActiveGatePod is capable of. Defines what functionality should be enabled (possible values: routing, kubernetes-monitoring, metrics-ingest).

**Comment by chrismuellner** [comment]
That's because the samples on `master` don't reflect the samples used in `v0.5.1`.
The documentation references the samples on the `v0.5.1` tag which do not have this capability.
