### ISSUE TITLE
Problem with CSI driver + CloudNativeFullStack mode + node taints

### ISSUE THREAD

**Issue by davcen** [Dynatrace/dynatrace-operator#733]
I'm trying to deploy Dynatrace on a Kubernetes Cluster (on Azure Kubernetes Services), using the "CloudNativeFullStack" mode and the official "dynatrace-operator" helm chart.

In this cluster i've a single node with a taint needed to isolate a specific workload, so i've configure the relevant toleration in the relevant section of the helm values file:
```
cloudNativeFullStack:
  enabled: true
  autoUpdate: false
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "sync"
      effect: "NoSchedule"
```

and i'm facing the following problem:

- the operator deploys two Daemonsets, "dynakube-oneagent" and "dynatrace-oneagent-csi-driver"
- the former inherits the toleration and spawns the pods on every node
- the latter doesn't inherit the toleration, so it spawns the pods on all nodes but the tainted one
- the "dynakube-oneagent" pod on tainted node remains in "ContainerCreating" status showing the following errors:
```
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  12m (x407 over 19h)    kubelet  Unable to attach or mount volumes: unmounted volumes=[osagent-storage], unattached volumes=[host-root osagent-storage]: timed out waiting for the condition
  Warning  FailedMount  2m26s (x593 over 19h)  kubelet  MountVolume.SetUp failed for volume "osagent-storage" : kubernetes.io/csi: mounter.SetUpAt failed to get CSI client: driver name csi.oneagent.dynatrace.com not found in the list of registered CSI drivers
```

I cant' see any option to specify a toleration for "dynatrace-oneagent-csi-driver" Daemonset in DynaKube custom resource.

Am i missing something?

**Comment by luhi-DT** [comment]
Hi, you can specify `tolerations` directly in the kubernetes-csi.yaml, which you used to deploy your `csi-driver` pods with and apply the modified file. There is no configuration option in the dynakube for that currently.
