### ISSUE TITLE
facing xxx.live.dynatrace.com/linux/oneagent: tag invalid: No bootstrapping-image 

### ISSUE THREAD

**Issue by ashishibm11** [Dynatrace/dynatrace-operator#735]
Dear team, 

when deploying oneagent daemonset on openshift 4.8 , getting below error 

**************************************************
 describe pod output - 

  Warning  Failed     130m (x4 over 131m)     kubelet            Failed to pull image "xxxxxx.live.dynatrace.com/linux/oneagent:latest": rpc error: code = Unknown desc = Error reading manifest latest in xxxxx.live.dynatrace.com/linux/oneagent: tag invalid: No bootstrapping-image found for version: 1.229.210.20220218-231302
  Warning  Failed     130m (x4 over 131m)     kubelet            Error: ErrImagePull
  Warning  Failed     129m (x6 over 131m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff    2m19s (x562 over 131m)  kubelet            Back-off pulling image 
  *********************************************************************************************
pod logs - 

Error from server (BadRequest): container "dynatrace-oneagent" in pod "dynakube-oneagent-4w2nf" is waiting to start: trying and failing to pull image

please help or advise.

**Comment by luhi-DT** [comment]
Hi, you can try to pull that image from one of your nodes like described here: https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/store-dynatrace-images-in-private-registries-kubernetes

If that is not working I would suggest to open a ticket at our official support as this is something, which probably has to do with your cluster setup: https://support.dynatrace.com/
