### ISSUE TITLE
[Feature request] SecurityContext

### ISSUE THREAD

**Issue by MaudVandevelde** [Dynatrace/dynatrace-operator#765]
Hello,
I need to have the possibilities to set securityContext for my deployment (due to security policy requirement in my company).

A bloc like this one could be added in spec/template/spec for deployment-operator and deployment webhook 

      {{- if .Values.securityContext }}
      securityContext: {{ toYaml .Values.securityContext | nindent 8 }}
        {{- end }}

**Comment by chrismuellner** [comment]
Since `v0.5.0` we restrict the Security Contexts for Operator components as much as possible.

**Comment by MaudVandevelde** [comment]
Hello,
I saw that the security context has been updated for the pod. But my company policy also required that I specify the following values runAdGroup, runAdUser, supplemtalGroups:
securityContext:
  fsGroup: 20000
  runAsGroup: 10000
  runAsNonRoot: true
  runAsUser: 10000
  supplementalGroups: [10000]

That s why I requested the possibility to set a securitycontext at container level.

-----
Moreover, regarding this helm chart, I also have another issue. The liveness check are set to /livez but they are exposed at /healthz
In https://github.com/Dynatrace/dynatrace-operator/blob/master/Dockerfile at raw 53: COPY --from=k8s.gcr.io/sig-storage/livenessprobe:v2.6.0 /livenessprobe /usr/local/bin
https://github.com/kubernetes-csi/livenessprobeLiveness :
The liveness probe is a sidecar container that exposes an HTTP /healthz endpoint, which serves as kubelet's livenessProbe hook<https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes> to monitor health of a CSI driver.

If I change the template replacing /livez by  /healthz it works.

Regards,
Maud

De : Christoph Muellner ***@***.***>
Envoyé : 9 mai 2022 08:16
À : Dynatrace/dynatrace-operator ***@***.***>
Cc : Vandevelde, Maud ***@***.***>; Author ***@***.***>
Objet : Re: [Dynatrace/dynatrace-operator] [Feature request] SecurityContext (Issue #765)


EXPÉDITEUR EXTERNE - Attention aux liens et aux pièces jointes
EXTERNAL SENDER - Beware of links and attachments

Since v0.5.0 we restrict the Security Contexts for Operator components as much as possible.

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDynatrace%2Fdynatrace-operator%2Fissues%2F765%23issuecomment-1121022814&data=05%7C01%7Cmaud.vandevelde%40ssq.ca%7Cca4a0331ae1f43ece12b08da31b5abad%7C5ad62f8ada9a4f5eb9c1649756c550ca%7C0%7C0%7C637876953583444896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b4405Vgy4zUm9XP9I4Z6lm4Dt5TUiUVI2dylT7jhJBQ%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVXMIVYDBCATVJ4DWUROVBTVJD6XXANCNFSM5U7DXQHA&data=05%7C01%7Cmaud.vandevelde%40ssq.ca%7Cca4a0331ae1f43ece12b08da31b5abad%7C5ad62f8ada9a4f5eb9c1649756c550ca%7C0%7C0%7C637876953583444896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=17fcsF0QBzIldP9TsJsb87fy%2BwYly2I2nZO%2FpEXNshA%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

Ce message et tous les fichiers attachés sont confidentiels et s'adressent exclusivement au(x) destinataire(s) indiqué(s) ci-dessus. Si vous recevez ce message par erreur, veuillez le retourner à l'expéditeur et le détruire. Tout usage, copie ou distribution non autorisés de ce courriel sont strictement interdits.

This message and any attachments are confidential and intended solely for the above-mentioned recipient(s). If you have received this message in error, please return it to the sender and delete it from your files. Unauthorized use, copying or distribution of this e-mail is strictly prohibited.

**Comment by MaudVandevelde** [comment]
Hi,
Regarding the second issue, I finally solve it changing version and appversion from 0.4.2 to 0.6.0 in https://github.com/Dynatrace/dynatrace-operator/blob/master/config/helm/chart/default/Chart.yaml
Regards,
Maud

De : Vandevelde, Maud
Envoyé : 9 mai 2022 10:03
À : Dynatrace/dynatrace-operator ***@***.***>
Cc : Vallée, Michel ***@***.***>
Objet : RE: [Dynatrace/dynatrace-operator] [Feature request] SecurityContext (Issue #765)

Hello,
I saw that the security context has been updated for the pod. But my company policy also required that I specify the following values runAdGroup, runAdUser, supplemtalGroups:
securityContext:
  fsGroup: 20000
  runAsGroup: 10000
  runAsNonRoot: true
  runAsUser: 10000
  supplementalGroups: [10000]

That s why I requested the possibility to set a securitycontext at container level.

-----
Moreover, regarding this helm chart, I also have another issue. The liveness check are set to /livez but they are exposed at /healthz
In https://github.com/Dynatrace/dynatrace-operator/blob/master/Dockerfile at raw 53: COPY --from=k8s.gcr.io/sig-storage/livenessprobe:v2.6.0 /livenessprobe /usr/local/bin
https://github.com/kubernetes-csi/livenessprobeLiveness :
The liveness probe is a sidecar container that exposes an HTTP /healthz endpoint, which serves as kubelet's livenessProbe hook<https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#container-probes> to monitor health of a CSI driver.

If I change the template replacing /livez by  /healthz it works.

Regards,
Maud

De : Christoph Muellner ***@***.******@***.***>>
Envoyé : 9 mai 2022 08:16
À : Dynatrace/dynatrace-operator ***@***.******@***.***>>
Cc : Vandevelde, Maud ***@***.******@***.***>>; Author ***@***.******@***.***>>
Objet : Re: [Dynatrace/dynatrace-operator] [Feature request] SecurityContext (Issue #765)


EXPÉDITEUR EXTERNE - Attention aux liens et aux pièces jointes
EXTERNAL SENDER - Beware of links and attachments

Since v0.5.0 we restrict the Security Contexts for Operator components as much as possible.

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDynatrace%2Fdynatrace-operator%2Fissues%2F765%23issuecomment-1121022814&data=05%7C01%7Cmaud.vandevelde%40ssq.ca%7Cca4a0331ae1f43ece12b08da31b5abad%7C5ad62f8ada9a4f5eb9c1649756c550ca%7C0%7C0%7C637876953583444896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b4405Vgy4zUm9XP9I4Z6lm4Dt5TUiUVI2dylT7jhJBQ%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVXMIVYDBCATVJ4DWUROVBTVJD6XXANCNFSM5U7DXQHA&data=05%7C01%7Cmaud.vandevelde%40ssq.ca%7Cca4a0331ae1f43ece12b08da31b5abad%7C5ad62f8ada9a4f5eb9c1649756c550ca%7C0%7C0%7C637876953583444896%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=17fcsF0QBzIldP9TsJsb87fy%2BwYly2I2nZO%2FpEXNshA%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

________________________________

Ce message et tous les fichiers attachés sont confidentiels et s'adressent exclusivement au(x) destinataire(s) indiqué(s) ci-dessus. Si vous recevez ce message par erreur, veuillez le retourner à l'expéditeur et le détruire. Tout usage, copie ou distribution non autorisés de ce courriel sont strictement interdits.

This message and any attachments are confidential and intended solely for the above-mentioned recipient(s). If you have received this message in error, please return it to the sender and delete it from your files. Unauthorized use, copying or distribution of this e-mail is strictly prohibited.
