### ISSUE TITLE
Forced unnecessary auto-injection of OpenShift deployer and build pods

### ISSUE THREAD

**Issue by d41k4n** [Dynatrace/dynatrace-operator#789]
It seems it's not possible to prevent auto-injection of deployer pods that are automatically created during rollout of DeploymentConfigs on OpenShift... This causes unnecessary delays in actual application starts and therefore IMO it should be possible to avoid it (either by default or by some configuration).

Note that it's not (easily) possible to annotate these pods with oneagent.dynatrace.com/inject=false as they are a built-in feature of OpenShift. FYI: Deployer pods are labeled with openshift.io/deployer-pod-for.name=...

Also, note that it's not always feasible to replace DeploymentConfigs with k8s-native "Deployment" objects so this isn't a possible workaround in all cases.

It seems the same issue is with build pods that are automatically spawned by BuildConfigs i.e. the Dynatrace operator will attempt to auto-inject them by default and so far I found no way how to annotate them with oneagent.dynatrace.com/inject=false ...

FYI: Our dynakube uses the oneAgent.applicationMonitoring feature and the operator version is 0.4.2 installed on OCP 4.8.

**Comment by ocpvkb** [comment]
We also have intensive discussions on this topic. You have to make the circle of exceptions even bigger when using other features in Kubernetes / Openshift. 

The situation is very interesting, e.g. with Serverless / Knative. Dynatrace partially destroys the actual benefit here. 

Pods are also injected unnecessarily with Openshift pipelines / tekton.

In our opinion, a blacklist function based on labels should be implemented in Dyntrace. This allows the exclusion of resources to be ideally controlled.

**Comment by luhi-DT** [comment]
Hi,
we provide the option to exclude certain pods by annotating them with the following annotations to exclude them from monitoring:

- `data-ingest.dynatrace.com/inject: false`
- `oneagent.dynatrace.com/inject: false`

More info here:
https://www.dynatrace.com/support/help/setup-and-configuration/setup-on-container-platforms/kubernetes/get-started-with-kubernetes-monitoring/dto-config-options-k8s#pod

However if you still feel that this does not satisfy you needs please create a feature requests in the [Dynatrace community](https://community.dynatrace.com/) rather than Github. This helps our team consolidate, rank, and prioritize important input like yours.

Please search for similar requests, collaborate, and ask questions using the link above. Remember to add the labels "kubernetes" and "dynatrace-operator" to help get the attention you deserve.

Thanks for your help!

**Comment by bd-bord1** [comment]
Hi @luhi-DT, 
I am running tests with this pod.yaml manifest and dyntrace one agent init container is still being created. 
We dont want dynatrace init container created to implement QoS.

```
apiVersion: v1
kind: Pod
metadata:
  name: qos-demo
  annotations:
    oneagent.dynatrace.com/inject: "false"
    dynakube.dynatrace.com/injected: "false"
	data-ingest.dynatrace.com/inject: "false"
spec:
  containers:
  - name: qos-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"

```

This are labels set on the ns:

```
Using project "client-prod-nbaa-devops-namespace" on server "https://api.ocpclientprod2.acic-navan.com:6443".
sh-5.1$ oc get ns client-prod-nbaa-devops-namespace --show-labels
NAME                                STATUS   AGE   LABELS
client-prod-nbaa-devops-namespace   Active   80d   dynakube.internal.dynatrace.com/instance=prod2,dynatrace.com/inject=false,kubernetes.io/metadata.name=client-prod-nbaa-devops-namespace,name=client-prod-nbaa-tag,openshift-pipelines.tekton.dev/namespace-reconcile-version=1.15.1,pod-security.kubernetes.io/audit-version=v1.24,pod-security.kubernetes.io/audit=privileged,pod-security.kubernetes.io/warn-version=v1.24,pod-security.kubernetes.io/warn=privileged
```
I removed this one:` dynakube.internal.dynatrace.com/instance=prod2`

but the dynatrace one agent init container is still being created.

Do you know how I could fix this?

Thank you.

**Comment by luhi-DT** [comment]
Please create a ticket for our support: one.dynatrace.com

**Comment by bd-bord1** [comment]
> Please create a ticket for our support: one.dynatrace.com

Thanks. Just did it. 👍
