### ISSUE TITLE
Add additional permissions required for PVC monitoring

### ISSUE THREAD

**Issue by PatrikSteuer** [Dynatrace/dynatrace-operator#815]
The PVC monitoring feature of containerized AGs requires the ``node/metrics`` ressource to be added to
dynatrace-kubernetes-monitoring  ClusterRole. It is descriped in within the [dynatrace documentation](https://www.dynatrace.com/support/help/how-to-use-dynatrace/infrastructure-monitoring/container-platform-monitoring/kubernetes-monitoring/monitor-pvc-metrics) otherwise PVC monitoring is not possible. 

I would suggest to add this so AGs deployed by the operator can be used for PVC monitoring.

**Comment by chrismuellner** [comment]
Since the PVC monitoring feature is opt-in this won't be included by default in the Operator installation to adhere to security best practices.

We will be adding it as an option to the helm chart in a future version.

**Comment by chrismuellner** [comment]
Will be added to the helm charts in a future release. See #859
