### ISSUE TITLE
Empty passwords for http proxy is forbidden

### ISSUE THREAD

**Issue by icereed** [Dynatrace/dynatrace-operator#886]
Hello,

unfortunately the latest version broke our setup since it suddenly does not allow empty proxy passwords.
We are using an http proxy without any authentication. This is now causing this error:

```
1 error(s) found in the Dynakube
 1. The DynaKube's specification has an invalid Proxy password value set. Make sure you don't use forbidden characters: space, apostrophe, backtick, comma, ampersand, equals sign, plus sign, percent sign, backslash.): error when creating "dynakube.new.yaml": admission webhook "webhook.dynatrace.com" denied the request: 
```
This is caused by this Regex:
https://github.com/Dynatrace/dynatrace-operator/blob/94ca5ca11138aaeddf5b778cbf96a4d11c95bfaa/src/webhook/validation/proxy_url.go#L65-L79

Please fix this by allowing empty proxy passwords.

**Comment by chrismuellner** [comment]
Fixed in v0.7.1
