### ISSUE TITLE
Feature Request: Support annotations for created resources

### ISSUE THREAD

**Issue by Logankwb** [Dynatrace/dynatrace-operator#923]
As a cluster admin, I'd like to be able to annotate the workload resources created by the operator so that they can be integrated with the other tools we run.

For example, in our clusters we run Istio. I'd like to have the option of using annotations to configure the OneAgent to have an Istio sidecar so I can use OneAgent-based prometheus scraping while also having strict settings for Istio mTLS.

And more generally, our internal standards dictate that we apply metadata to all workloads, so I'd like to be able to do that using annotations via the operator

**Comment by Logankwb** [comment]
I'd be happy to submit a PR for this, although it looks like a large-ish change

**Comment by chrismuellner** [comment]
I added the option to add custom annotations to operator managed components to our roadmap, but can't give you an ETA now.

**Comment by mreider** [comment]
There's an additional vote for this via the Dynatrace Community forum:
 
https://community.dynatrace.com/t5/Dynatrace-product-ideas/RFE-Add-Annotations-for-ActiveGate-Pods/idi-p/192030

**Comment by chrismuellner** [comment]
Starting with v0.9.0 it's possible to configure `annotations` and `labels` for both the oneagent and the activegate in the Dynakube.

We will update the samples accordingly.

**Comment by Logankwb** [comment]
Also for posterity, for my use-case (Istio), I could actually just use labels after all 😄
