### ISSUE TITLE
DT Operator v0.7.1 Helm installation not bring up Activegate and OneAgent

### ISSUE THREAD

**Issue by ntt2k** [Dynatrace/dynatrace-operator#941]
DT Operator v0.7.1 Helm installation not bring up ActiveGate and OneAgent

Only Operator & Webhook are up, no ActiveGate or OneAgent ?! -->

![Screen Shot 2022-07-08 at 11 36 28 PM](https://user-images.githubusercontent.com/4227421/178091773-aef3d6fb-ee00-485b-bd07-41bab30915fd.png)

**Comment by chrismuellner** [comment]
Starting with v0.7.0 the Dynakube is no longer included in the Helm chart.

If you upgrade from a previous helm release the Dynakube should still be there as it's not managed by Helm. If you do a fresh install, you will have to apply a Dynakube after the Helm release is installed, see official documentation for more.
