### ISSUE TITLE
Agent Version behaviour

### ISSUE THREAD

**Issue by pahofmann** [Dynatrace/dynatrace-operator#948]
I recently ran into an issue when deploying operator v0.6.0. 

I set a specific agent version in the CR, but it still used _latest_. 
It then failed to get the agent, because the Agent Version in the environment was pinned to a minor version that was recalled (no longer available).

I found #937 which suggest that ignoring the version in the CR is not as expected. 

What is the behaviour to be expected with 0.7.0 then? 
If no version is defined in the CR it will get the latest available, honoring the max version configured if automatic updates are disabled for the environment? 
If a lower version is set it will use that if available?

If the set version isn't available, will it fail or use latest as a fallback?

**Comment by pahofmann** [comment]
Great, thanks! Another question though:

We have financial/insurance customers with rigorous testing schemes. They test one spcific OneAgent _Revision_ and dann roll that out through their stages.

 With the operator we have a problem when an agent version get's recalled. It then is no longer available on the cluster and the OneAgent Pod can't download it.  Outside OpenShift we use the downloaded installer in that exact revision for the roll out anyway.

 Is there any way to provide the agent binary to the OneAgent pod, so that it doesn't even try to download it?
AFAIK it caches the installer anyway, so can we provide it to the pod via a volume, so it find the correct revision locally even if it was recalled from the cluster?

**Comment by chrismuellner** [comment]
With `v0.7.0` we've added the `codeModulesImage` field. This allows you to store a specific oneagent version on a private registry and use that in the CSI driver (see [official documentation](https://www.dynatrace.com/support/help/shortlink/air-gapped-kubernetes#code-modules)).
The version will only change when you update the image tag and as long as the registry is on is available the oneagent version can be used as well.

**Comment by pahofmann** [comment]
Perfect, that's exactly what we need! Thanks for the update, hadn't seen that new doc entry for 0.7.0 yet.
