### ISSUE TITLE
Security issues for 0.7.2

### ISSUE THREAD

**Issue by keith-e-dynatrace** [Dynatrace/dynatrace-operator#972]
Hi developers, I have a user who is wanting to use the operator, but has found the following security issues with the Operator's use of GoLang < 18.1. Please see attached spreadsheet. We are currently at GoLang 18. Is there an ETA on when we might update to > 18.1. I believe it should resolve these issues!

Keith Ellis

[dynatrace-operator-v0.7.2-scan-results-gdms.xlsx](https://github.com/Dynatrace/dynatrace-operator/files/9114648/dynatrace-operator-v0.7.2-scan-results-gdms.xlsx)
[dynatrace-operator-v0.7.2-scan-results-gdms.xlsx](https://github.com/Dynatrace/dynatrace-operator/files/9114648/dynatrace-operator-v0.7.2-scan-results-gdms.xlsx)
[dynatrace-operator-v0.7.2-scan-results.zip](https://github.com/Dynatrace/dynatrace-operator/files/9114652/dynatrace-operator-v0.7.2-scan-results.zip)
[dynatrace-operator-v0.7.2-scan-results.zip](https://github.com/Dynatrace/dynatrace-operator/files/9114652/dynatrace-operator-v0.7.2-scan-results.zip)

**Comment by luhi-DT** [comment]
0.8.0 is already released therfore this scan is outdate, however we will release 0.8.1 with an updated base image, where most vulnerabilities are fixed. The go 1.17.3 vulnerabilities are coming from a third party, which is included in our image, however we are at the most recent version there. Therefore there is not much we can do.
