### ISSUE TITLE
Issue SCC v0.7.2 on Openshift

### ISSUE THREAD

**Issue by ocpvkb** [Dynatrace/dynatrace-operator#978]
Error: 
"container has runAsNonRoot and image will run as root (pod: "dynakube-ea-oneagent-5lgw5_dynatrace(f60eda44-a753-4581-b2a5-8ba4b7819d8b)", container: dynatrace-oneagent)"

Deployed CR:
`
apiVersion: dynatrace.com/v1beta1
kind: DynaKube
metadata:
  name: dynakube-ea
  namespace: dynatrace
spec:
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
      - dynatrace-api
    resources:
      limits:
        cpu: 2500m
        memory: 1.5Gi
      requests:
        cpu: 1500m
        memory: 1Gi
  apiUrl: 'https://server123.de/e/8e6300ef-656b-4fe0-92ab-cce168a73f2b/api'
  oneAgent:
    classicFullStack:
      args:
        - '--set-host-group=mygroup'
      oneAgentResources:
        limits:
          cpu: 500m
          memory: 1.5Gi
        requests:
          cpu: 300m
          memory: 512Mi
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
  trustedCAs: dynakube-ca
`
It seems that there's an issue with the scc's for unprivileged and privileged service account. They are granted to the same service account(unprivileged).
That should be checked.

**Comment by chrismuellner** [comment]
How did you install the Operator? Is this just Openshift or using OLM?
Was it an upgrade from a previous version? If yes, what version?

**Comment by ocpvkb** [comment]
We installed the operator via the default process:

oc apply -f https://github.com/Dynatrace/dynatrace-operator/releases/download/v0.7.2/openshift.yaml

We tested both options: 
Upgrade from 0.5.1 and fresh install from scratch with 0.7.2. Both cases are not successful.

BTW: The Version 0.7.1 is also not running in Openshift ENV because of SCC isues. (The basic Dynatrace Operator Pod can't be created because of scc vioalation... (anyUID..)

**Comment by chrismuellner** [comment]
Please use the following feature flag to set the oneagent to run as privileged:
```
kubectl annotate dynakube dynakube-ea feature.dynatrace.om/oneagent-privileged=true
```

This should allow the correct SCC to be matched so the pods can be created and have the required permissions.

**Comment by ocpvkb** [comment]
works like a charm after finding the typo ".om".
Shouldn't that be included in the cr.yaml (e.g. classicFullStack.yaml) by default?
