### ISSUE TITLE
Make bundle generates manifests for k8s only

### ISSUE THREAD

**Issue by jsm84** [Dynatrace/dynatrace-operator#984]
#974 introduced a slight regression where manifests now only get generated for the kubernetes platform, instead of respecting the `PLATFORM` variable (kubernetes|openshift) and building manifests for the desired platform (set to `openshift` by default).

This seems to be causing bundles built for the OpenShift platform to be missing SCC's.

**Comment by meik99** [comment]
Updated https://github.com/Dynatrace/dynatrace-operator/pull/985 and set to auto-merge.
